# ============================================================================
# 文件作用：Text-to-SQL 服务，基于 Vanna 0.7.1 + ChromaDB 0.5.21 实现自然语言转 SQL
# 使用多重继承方式（vanna.ollama.Ollama + vanna.chromadb.ChromaDB_VectorStore）
# ============================================================================

import os
import time
from app.core.config import settings
from app.utils.logger import logger

# 禁用 ChromaDB 遥测（避免 Failed to send telemetry event 警告）
os.environ["ANONYMIZED_TELEMETRY"] = "False"

from vanna.ollama import Ollama
from vanna.chromadb import ChromaDB_VectorStore

class MyVanna(ChromaDB_VectorStore, Ollama):
    """
    自定义 Vanna 类，兼容 vanna 0.7.1 和 chromadb 0.5.21。
    使用 ChromaDB 持久化目录，Ollama 作为 LLM。
    """
    def __init__(self):
        logger.info("初始化 MyVanna 实例...")
        
        # ---------- 1. 初始化 ChromaDB_VectorStore ----------
        # 持久化目录（确保存在）
        chroma_persist_dir = "/workspace/data/vectors/chroma_db"
        os.makedirs(chroma_persist_dir, exist_ok=True)
        
        # 通过 config 传递 persist_directory
        ChromaDB_VectorStore.__init__(self, config={"persist_directory": chroma_persist_dir})
        logger.info(f"ChromaDB 初始化完成，持久化路径: {chroma_persist_dir}")
        
        # ---------- 2. 初始化 Ollama ----------
        Ollama.__init__(self, config={
            'model': settings.LLM_MODEL,
            'host': settings.OLLAMA_BASE_URL
        })
        logger.info(f"Ollama 初始化完成，模型: {settings.LLM_MODEL}, 地址: {settings.OLLAMA_BASE_URL}")
        
        logger.info("Vanna 实例创建成功 (v0.7.1)")

# 全局单例
vn = None

def init_vanna():
    """初始化 Vanna，并训练所有 DDL 和文档（首次启动时调用）"""
    global vn
    if vn is not None:
        logger.info("Vanna 已经初始化，跳过")
        return
    
    logger.info("开始初始化 Vanna (v0.7.1)...")
    start_time = time.time()
    vn = MyVanna()
    
    # ========== 训练数据库表结构（DDL） ==========
    # 注意：以下 DDL 仅为示例，实际请替换为您自己的完整 DDL 字符串
    ddl_user_behavior = """
    -- 1. 用户行为表（存储每月用户使用情况）
    CREATE TABLE user_behavior (
    month String COMMENT '数据统计的月份',
    user_id String COMMENT '系统内唯一标识用户的编号',
    city_id String COMMENT '用户号码归属的地市级行政区域',
    age Int32 COMMENT '用户的实际年龄',
    sex_id String COMMENT '用户的性别信息',
    prv1_userstatus_id String COMMENT '用户上个月的状态（如正常、停机、预销户等）',
    star_level String COMMENT '用户星级：根据用户消费能力、信用度、在网时长等综合因素评定的用户等级',
    star_level_b Int8 COMMENT '对比当前月与上月用户星级是否发生变化',
    is_jxhm Int8 COMMENT '判断用户号码是否属于吉祥号',
    brand_id Int8 COMMENT '动感地带为1，神州行为2、全球通为3，其他为4',
    user_online Int32 COMMENT '用户从入网到当前时间的累计在网时长',
    arpu120_user Int8 COMMENT '根据当月ARPU值是否达到一定阈值（如120元）来判断是否为中高端客户',
    bd_arpu120_user Int8 COMMENT '对比当前月与上月中高端客户标识是否发生变化',
    credit_id String COMMENT '根据用户的缴费记录、欠费情况等评估的信用等级',
    credit_id_b Int8 COMMENT '对比当前月与上月用户信用度等级是否发生变化',
    paytype21_user Int8 COMMENT '判断用户是否通过代付或托收方式支付费用',
    is_acct_counts Int8 COMMENT '判断用户是否与其他用户合并账单',
    is_rhtc Int8 COMMENT '判断用户是否使用包含语音、流量、宽带等多业务的融合套餐',
    qx_rhtc_3month Int8 COMMENT '近三月存在"是否融合套餐用户"=0 and 三月前月表"是否融合套餐用户"=1',
    xz_rhtc_3month Int8 COMMENT '近三月存在"是否融合套餐用户"=1 and 三月前月表"是否融合套餐用户"=0',
    is_jttf Int8 COMMENT '判断用户是否属于集团统付或代付用户',
    qx_jttf_3month Int8 COMMENT '近三个月内是否存在"是否集团统付/代付"从1变为0的情况',
    regiontype_id3 Int8 COMMENT '根据用户归属地判断是否为农村用户',
    student_flag Int8 COMMENT '判断用户是否为学生身份',
    month_new_mark Int8 COMMENT '判断用户是否为当月新入网用户',
    month_new_mark_6month Int8 COMMENT '判断用户是否为近6个月内新入网用户',
    zero_mark Int8 COMMENT '判断用户当月是否无任何通信行为（如通话、流量使用等）',
    arpu_fluctuate_mark Int8 COMMENT '用户消费金额波动较大，通常指ARPU值波动率超过一定阈值',
    arpu_stabilize_mark Int8 COMMENT '用户消费金额较为稳定，通常指ARPU值波动率低于一定阈值',
    active_mark Int8 COMMENT '判断用户当月是否有通信行为（如通话、短信、流量使用等）',
    dou_mark Int8 COMMENT '判断用户当月是否有流量使用行为',
    is_ll_dh Int8 COMMENT '是否通话用户=0 and dou>1G',
    is_yy_dh Int8 COMMENT '主叫通话次数>1 and dou<50M',
    is_dh_2month Int8 COMMENT '连续2月是否流量单活用户 or 是否语音单活用户',
    is_dh_3month Int8 COMMENT '连续3月是否流量单活用户 or 是否语音单活用户',
    vip_mark Int8 COMMENT '判断用户是否为企业或集团大客户',
    ys_yd_yh Int8 COMMENT '根据用户行为异常（如突然停机、大量投诉等）判断是否为疑似异动用户',
    mon_consume_id String COMMENT '根据用户月消费金额划分的消费层次（如低、中、高）',
    call_mark Int8 COMMENT '判断用户当月是否有通话行为',
    school_flag Int8 COMMENT '判断用户归属地是否为校园区域',
    family_main Int8 COMMENT '判断用户是否为亲情网主卡用户',
    is_family Int8 COMMENT '判断用户当月是否为亲情网用户',
    qx_family_3month Int8 COMMENT '近三个月内是否存在取消亲情网的情况',
    owe_fee Decimal(18,2) COMMENT '用户月末的欠费金额',
    owe_fee_pre1 Decimal(18,2) COMMENT '用户上月末的欠费金额',
    owe_fee_pre2 Decimal(18,2) COMMENT '用户上上月末的欠费金额',
    zs_fee Decimal(18,2) COMMENT '用户当月获得的赠送费用金额',
    zs_fee_v Decimal(10,4) COMMENT '赠送费用占当月出账收入的比例',
    zs_fee_time Date COMMENT '赠送费用的有效期截止时间',
    PAY_FEE Decimal(18,2) COMMENT '用户当月的缴费金额',
    PAY_FEE_pre1 Decimal(18,2) COMMENT '用户上月的缴费金额',
    PAY_FEE_pre2 Decimal(18,2) COMMENT '用户上上月的缴费金额',
    PAY_FEE_v Decimal(10,4) COMMENT '当月缴费金额与上月相比的增长比例',
    pay_counts Int32 COMMENT '用户当月的缴费次数',
    pay_counts_pre1 Int32 COMMENT '用户上月的缴费次数',
    pay_counts_pre2 Int32 COMMENT '用户上上月的缴费次数',
    pay_counts_v Decimal(10,4) COMMENT '当月缴费次数与上月相比的增长比例',
    pay_counts_3month Int32 COMMENT '用户近三个月的累计缴费次数',
    pay_fee_3month Decimal(18,2) COMMENT '用户近三个月的累计缴费金额',
    pve_amount Decimal(18,2) COMMENT '用户当月账户余额',
    pve1_amount Decimal(18,2) COMMENT '用户上月账户余额',
    pve2_amount Decimal(18,2) COMMENT '用户上上月账户余额',
    prepay_bal Decimal(18,2) COMMENT '用户当月月末的账户余额',
    prepay_bal_v Decimal(10,4) COMMENT '当月月末账户余额与上月相比的增长比例',
    amount_bd Decimal(10,4) COMMENT '用户账户余额的波动情况，通常用标准差计算',
    credit Decimal(18,2) COMMENT '用户当月的透支额度',
    credit_pve1 Decimal(18,2) COMMENT '用户上月的透支额度',
    credit_pve2 Decimal(18,2) COMMENT '用户上上月的透支额度',
    arpu Decimal(10,2) COMMENT '每用户平均收入，计算公式为总收入/用户数',
    arpu_pve1 Decimal(10,2) COMMENT '上月的每用户平均收入',
    arpu_pve2 Decimal(10,2) COMMENT '上上月的每用户平均收入',
    avg_3mon_fee Decimal(10,2) COMMENT '近三个月的每用户平均收入均值',
    arpu_bd Decimal(10,4) COMMENT '近三个月ARPU值的波动情况，通常用标准差计算',
    arpu_pve1_v Decimal(10,4) COMMENT '当月出账收入与上月相比的下降比例',
    avg_gprsplan_fee_3m Decimal(10,2) COMMENT '近三个月GPRS套餐费用的平均值',
    newbusi_fee Decimal(18,2) COMMENT '用户当月新业务（如增值业务）的费用',
    newbusi_fee1 Decimal(18,2) COMMENT '用户上月新业务的费用',
    newbusi_fee_v Decimal(10,4) COMMENT '新业务费用与上月相比的变化情况',
    LAM_YZF_FEE Decimal(18,2) COMMENT '用户当月的月租费用',
    LAM_YZF_FEE_v Decimal(10,4) COMMENT '当月月租费用与上月相比的增长比例',
    LAM_YZF_FEE_pre1 Decimal(18,2) COMMENT '用户上月的月租费用',
    LAM_YZF_FEE_pre2 Decimal(18,2) COMMENT '用户上上月的月租费用',
    call_fee Decimal(18,2) COMMENT '用户当月的通话费用',
    call_FEE_v Decimal(10,4) COMMENT '当月通话费用与上月相比的增长比例',
    gprs_fee Decimal(18,2) COMMENT '用户当月的流量费用',
    gprs_fee_v Decimal(10,4) COMMENT '当月流量费用与上月相比的增长比例',
    tax_on_yuezu Decimal(18,2) COMMENT '用户当月实际收取的套餐费用',
    pre_tax_on_yuezu Decimal(18,2) COMMENT '用户上月实际收取的套餐费用',
    pre1_tax_on_yuezu Decimal(18,2) COMMENT '用户上上月实际收取的套餐费用',
    zhekou Decimal(18,2) COMMENT '用户当月享受的折扣或折让费用（通过系统充值）',
    pre_zhekou Decimal(18,2) COMMENT '用户上月享受的折扣或折让费用',
    pre1_zhekou Decimal(18,2) COMMENT '用户上上月享受的折扣或折让费用',
    zhekou_v Decimal(10,4) COMMENT '当月折扣折让费用占ARPU的比例',
    is_tc_free Int8 COMMENT '判断用户是否享受套餐减免优惠',
    jm_tc_sy_times Int32 COMMENT '套餐减免优惠的剩余有效期',
    tc_sy_times Int32 COMMENT '用户当前套餐的剩余有效期',
    LAM_MYTHF_FEE Decimal(18,2) COMMENT '用户当月产生的漫游费用',
    LAM_MYTHF_FEE_pre1 Decimal(18,2) COMMENT '用户上月产生的漫游费用',
    LAM_MYTHF_FEE_pre2 Decimal(18,2) COMMENT '用户上上月产生的漫游费用',
    LAM_MYTHF_FEE_v Decimal(10,4) COMMENT '当月漫游费用与上月相比的增长比例',
    plan_id_bd Int8 COMMENT '判断用户主套餐是否与上月不同',
    plan_fee Decimal(18,2) COMMENT '用户当前主套餐的价格',
    plan_fee_pre1 Decimal(18,2) COMMENT '用户上月主套餐的价格',
    plan_fee_pre2 Decimal(18,2) COMMENT '用户上上月主套餐的价格',
    tc_use_times Int32 COMMENT '用户使用最新套餐的累计时长',
    plan_fee_bd Int8 COMMENT '判断用户主套餐价格是否与上月不同',
    plan_six_num Int32 COMMENT '用户近6个月内更换套餐的次数',
    is_jd Int8 COMMENT '判断用户当月是否将套餐降档',
    is_jd_3month Int8 COMMENT '判断用户近3个月内是否将套餐降档',
    is_5gtb Int8 COMMENT '判断用户近3个月内是否办理了5G套包',
    plan_5g_mark Int8 COMMENT '判断用户是否使用5G套餐',
    arpu_momr Decimal(10,4) COMMENT '当月ARPU与上月ARPU的环比变化比例',
    pve_arpu_momr Decimal(10,4) COMMENT '上月ARPU与上上月ARPU的环比变化比例',
    gprsplan_fee Decimal(18,2) COMMENT '用户当月GPRS套餐费用',
    lam_yzf_fee_pve1 Decimal(18,2) COMMENT '用户上月套餐费用',
    lam_yzf_fee_pve2 Decimal(18,2) COMMENT '用户上上月套餐费用',
    last_gprs_billing_flows Int64 COMMENT '用户上月GPRS计费流量（单位：字节）',
    before_last_gprs_billing_flows Int64 COMMENT '用户上上月GPRS计费流量（单位：字节）',
    over_flow_3month Int64 COMMENT '用户近3个月内超出套餐的流量（单位：MB）',
    is_lower_arpu Int8 COMMENT 'ARPU低于28元',
    is_bxl_xs3 Int8 COMMENT '近3月出现超限速情况',
    is_gprs_ct_fee_3month_h Int8 COMMENT '近3月月均流量超套费用大于10元',
    is_yuyin_ct_fee_3month_h Int8 COMMENT '近3月月均语音超套费用大于10元',
    is_arpu_high Int8 COMMENT '近3月月均arpu/近3月月均主套餐费用大于等于150%',
    is_lower_arpu3 Int8 COMMENT '近3月转过低资费（28以下）',
    DUAL_CARD_USER_MARK Int8 COMMENT '0：否 1：是',
    is_llb Int8 COMMENT '判断用户当月是否订购了流量包',
    prv1_llb Int8 COMMENT '判断用户上月是否订购了流量包',
    prv2_llb Int8 COMMENT '判断用户上上月是否订购了流量包',
    llb_cnt Int32 COMMENT '用户当前生效的流量包数量',
    is_dxb Int8 COMMENT '判断用户是否订购了定向流量包（如视频、音乐等特定应用流量包）',
    llb_should_fee Decimal(18,2) COMMENT '用户当月订购流量包的总费用',
    is_ywzk Int8 COMMENT '判断用户当月是否为异网主卡用户',
    new_ywsk Int8 COMMENT '判断用户当月是否新增了异网双卡',
    prv1_new_ywsk Int8 COMMENT '判断用户上月是否新增了异网双卡',
    bwsk_new Int8 COMMENT '判断用户当月是否新增了本网双卡',
    prv1_new_bwsk Int8 COMMENT '判断用户上月是否新增了本网双卡',
    is_ywsk Int8 COMMENT '判断用户当月是否为异网双卡用户',
    is_bwsk Int8 COMMENT '判断用户当月是否为本网双卡用户',
    is_zdhy Int8 COMMENT '判断用户是否使用合约机',
    imei_online Int32 COMMENT '用户终端设备的在网时长',
    HIS_IMEI_TRACK Int32 COMMENT '用户历史平均换机周期',
    IMEI_START Date COMMENT '用户上次更换终端的时间',
    PRE_TERM_PRICE Decimal(18,2) COMMENT '用户上次终端设备的裸机价格',
    SOURCE_IMEI_LONG Int32 COMMENT '用户终端设备的IMEI对应的网龄',
    TRACK_ID String COMMENT '根据用户换机周期划分的档次（如短周期、中周期、长周期）',
    out_call_duration_m Int64 COMMENT '用户当月主叫计费通话时长',
    out_call_duration_m1 Int64 COMMENT '用户上月主叫计费通话时长',
    out_call_duration_m2 Int64 COMMENT '用户上上月主叫计费通话时长',
    out_call_duration_m3 Int64 COMMENT '用户前三月主叫计费通话时长',
    avg_call_duration_m_prv_3m Int64 COMMENT '用户近3个月平均总计费通话时长',
    avg_out_call_duration_m_3m Int64 COMMENT '用户近3个月平均主叫计费通话时长',
    avg_in_call_dura_3m Int64 COMMENT '用户近3个月平均被叫计费通话时长',
    call_dura_v Decimal(10,4) COMMENT '当月计费时长与上月相比的下降比例',
    call_counts Int32 COMMENT '用户当月的通话次数',
    avg_callcount_3m Int32 COMMENT '用户近3个月平均通话次数',
    call_counts_bd Decimal(10,4) COMMENT '用户近3个月通话次数的波动情况',
    call_counts_prv1 Int32 COMMENT '用户上月的通话次数',
    call_counts_prv2 Int32 COMMENT '用户上上月的通话次数',
    call_counts_prv3 Int32 COMMENT '用户前三月的通话次数',
    call_duration_m Int64 COMMENT '用户当月的通话时长',
    avg_callduration_3m Int64 COMMENT '用户近3个月平均通话时长',
    call_duration_m_bd Decimal(10,4) COMMENT '用户近3个月通话时长的波动情况',
    call_duration_m_prv1 Int64 COMMENT '用户上月的通话时长',
    call_duration_m_prv2 Int64 COMMENT '用户上上月的通话时长',
    call_duration_m_prv3 Int64 COMMENT '用户前三月的通话时长',
    call_duration_m_prv_v Decimal(10,4) COMMENT '当月通话时长与上月相比的增长比例',
    out_call_duration Int64 COMMENT '用户当月的主叫通话时长',
    out_call_dura_prv1 Int64 COMMENT '用户上月的主叫通话时长',
    out_call_dura_prv2 Int64 COMMENT '用户上上月的主叫通话时长',
    out_call_counts Int32 COMMENT '用户当月的主叫通话次数',
    out_call_counts1 Int32 COMMENT '用户上月的主叫通话次数',
    out_call_counts2 Int32 COMMENT '用户上上月的主叫通话次数',
    out_call_counts_v Decimal(10,4) COMMENT '当月主叫次数与上月相比的增长比例',
    in_call_duration_m Int64 COMMENT '用户当月的被叫通话时长',
    in_call_duration_m_pre1 Int64 COMMENT '用户上月的被叫通话时长',
    in_call_duration_m_v Decimal(10,4) COMMENT '当月被叫时长与上月相比的增长比例',
    in_call_counts Int32 COMMENT '用户当月的被叫通话次数',
    in_call_counts1 Int32 COMMENT '用户上月的被叫通话次数',
    in_call_counts2 Int32 COMMENT '用户上上月的被叫通话次数',
    in_call_counts_v Decimal(10,4) COMMENT '当月被叫次数与上月相比的增长比例',
    out_in_call_d_v Decimal(10,4) COMMENT '主叫与被叫通话时长的比例',
    inner_call_v Decimal(10,4) COMMENT '本网通话时长占总通话时长的比例',
    out_in_call_count_v Decimal(10,4) COMMENT '主叫通话次数占总通话次数的比例',
    callfw_counts Int32 COMMENT '用户当月的呼叫转移次数',
    callfw_counts_v Decimal(10,4) COMMENT '当月呼转次数与上月相比的增长比例',
    callfw_counts1 Int32 COMMENT '用户当月呼转至外网的次数',
    call_opp_counts1 Int32 COMMENT '用户当月通话对端号码的数量（即语言交往圈人数）',
    call_opp_counts_v Decimal(10,4) COMMENT '当月通话对端号个数与上月相比的增长比例',
    avg_call_counts_3m Int32 COMMENT '用户近3个月平均总通话次数',
    avg_out_call_counts_prv_3m Int32 COMMENT '用户近3个月平均主叫通话次数',
    avg_in_call_counts_3m Int32 COMMENT '用户近3个月平均被叫通话次数',
    out_call_counts_3bd Decimal(10,4) COMMENT '用户近3个月主叫通话次数的波动情况',
    in_call_counts_3bd Decimal(10,4) COMMENT '用户近3个月被叫通话次数的波动情况',
    CALL_OPP_OUT_COUNTS Int32 COMMENT '用户N月本网主叫交往圈人数',
    prv1_call_opp_out_counts Int32 COMMENT '用户N-1月本网主叫交往圈人数',
    prv2_call_opp_out_counts Int32 COMMENT '用户N-2月本网主叫交往圈人数',
    call_opp_in_counts Int32 COMMENT '用户N月本网被叫交往圈人数',
    prv1_call_opp_in_counts Int32 COMMENT '用户N-1月本网被叫交往圈人数',
    prv2_call_opp_in_counts Int32 COMMENT '用户N-2月本网被叫交往圈人数',
    p1_yw_call_opp_counts_momr Decimal(10,4) COMMENT '本月与上月异网交往圈人数的环比变化比例',
    p2_yw_call_opp_counts_momr Decimal(10,4) COMMENT '上月与上上月异网交往圈人数的环比变化比例',
    all_bhd Decimal(10,4) COMMENT '用户当月流量使用量占套餐流量的比例',
    dou Int64 COMMENT '用户N月的流量使用量',
    dou_bd Decimal(10,4) COMMENT '用户流量使用量的波动情况',
    dou_hb_rate Decimal(10,4) COMMENT '当月流量使用量与上月相比的增长比例',
    zero_call_days Int32 COMMENT '用户当月未进行任何通话的天数',
    tc_userd Int64 COMMENT '用户主套餐内的流量使用量',
    tc_bhd Decimal(10,4) COMMENT '用户主套餐流量使用量占套餐总量的比例',
    llb_userd Int64 COMMENT '用户订购的流量包使用量',
    llb_bhd Decimal(10,4) COMMENT '用户流量包使用量占流量包总量的比例',
    bill_gprs_userd Int64 COMMENT '用户计费流量（超出套餐部分）的使用量',
    bill_bhd Decimal(10,4) COMMENT '用户计费流量使用量占计费流量上限的比例',
    dx_userd Int64 COMMENT '用户定向流量（如视频、音乐等）的使用量',
    dx_bhd Decimal(10,4) COMMENT '用户定向流量使用量占定向流量总量的比例',
    jiezhuan_userd Int64 COMMENT '用户结转流量（上月未用完的流量）的使用量',
    jiezhuan_bhd Decimal(10,4) COMMENT '用户结转流量使用量占结转流量总量的比例',
    is_llyz Int8 COMMENT '指饱和度>90%后日均流量使用量较90%之前日均流量使用量下降幅度>50%的用户',
    liul_unlimit Int8 COMMENT '判断用户当月是否使用不限量流量套餐',
    pve1_dou Int64 COMMENT '用户N-1月的流量使用量',
    pve2_dou Int64 COMMENT '用户N-2月的流量使用量',
    dou_hb Decimal(10,4) COMMENT '当月流量使用量与上月相比的环比变化比例',
    pre1_liul_unlimit Int8 COMMENT '判断用户N-1月是否使用不限量流量套餐',
    pre2_liul_unlimit Int8 COMMENT '判断用户N-2月是否使用不限量流量套餐',
    gprs_5g_flow_m Decimal(10,2) COMMENT '用户当月5G网络产生的流量（单位：GB）',
    all_gprs_lte_flows Decimal(10,2) COMMENT '用户当月4G网络产生的流量（单位：GB）',
    sn_gprs_flows Decimal(10,2) COMMENT '用户当月在省内产生的全部流量（单位：GB）',
    sw_gprs_flows Decimal(10,2) COMMENT '用户当月在省外产生的全部流量（单位：GB）',
    gprs_left_res Int64 COMMENT '用户套餐内剩余的流量（单位：MB）',
    jz_gprs_res Int64 COMMENT '用户上月结转的流量（单位：MB）',
    jz_gprs_res_pve1 Int64 COMMENT '用户上上月结转的流量（单位：MB）',
    jz_gprs_res_pve2 Int64 COMMENT '用户前三个月结转的流量（单位：MB）',
    is_ct_3month Int8 COMMENT '判断用户是否连续3个月语音使用量超出套餐',
    call_duration_fee_3momth Decimal(18,2) COMMENT '用户近3个月超出套餐的语音费用（单位：元）',
    llb_should_fee_temp Decimal(18,2) COMMENT '用户当月订购流量包的总费用',
    gprs_ct Int64 COMMENT '用户N月超出套餐的流量',
    prv1_gprs_ct Int64 COMMENT '用户N-1月超出套餐的流量',
    prv2_gprs_ct Int64 COMMENT '用户N-2月超出套餐的流量',
    gprs_ct_hb Decimal(10,4) COMMENT '当月超套流量与上月相比的环比变化比例',
    is_gprs_ct_3month Int8 COMMENT '判断用户是否连续3个月流量使用量超出套餐',
    llb_5g_mark Int8 COMMENT '判断用户是否订购了5G流量包',
    c_yz_fee Decimal(18,2) COMMENT '用户当月超出套餐产生的费用',
    c_yz_fee_v Decimal(10,4) COMMENT '当月套外费用与上月相比的增长比例',
    gprs_flow_fee Decimal(18,2) COMMENT '用户当月超出套餐产生的流量费用',
    gprs_flow_fee_v Decimal(10,4) COMMENT '当月套外流量费用与上月相比的增长比例',
    yuyin_fee_3month Decimal(18,2) COMMENT '用户近3个月平均每月语音费用',
    yuyin_ct_fee_3month Decimal(18,2) COMMENT '用户近3个月平均每月超出套餐的语音费用',
    gprs_fee_3month Decimal(18,2) COMMENT '用户近3个月平均每月流量费用',
    gprs_ct_fee_3month Decimal(18,2) COMMENT '用户近3个月平均每月超出套餐的流量费用',
    toll_call_opp_counts Int32 COMMENT '用户国内长途通话的交往圈人数',
    roam_duration_m1 Int64 COMMENT '用户上月漫游通话时长（单位：分钟）',
    roam_duration_m2 Int64 COMMENT '用户上上月漫游通话时长（单位：分钟）',
    roam_duration_m3 Int64 COMMENT '用户前三月漫游通话时长（单位：分钟）',
    roam_counts_v Decimal(10,4) COMMENT '漫游通话次数占总通话次数的比例',
    sw_call_duration_m Int64 COMMENT '用户当月省外漫游的话务量',
    sw_call_duration_m_v Decimal(10,4) COMMENT '当月省外漫游话务量与上月相比的增长比例',
    long_out_dou Int8 COMMENT '判断用户是否为长期漫出用户（如连续多月漫出）',
    out_sw_days Int32 COMMENT '用户当月漫出外省的天数',
    out_sw_gprs Int64 COMMENT '用户当月漫出外省产生的流量',
    prv1_out_sw_days Int32 COMMENT '用户上月漫出外省的天数',
    prv1_out_sw_gprs Int64 COMMENT '用户上月漫出外省产生的流量',
    prv2_out_sw_days Int32 COMMENT '用户上上月漫出外省的天数',
    prv2_out_sw_gprs Int64 COMMENT '用户上上月漫出外省产生的流量',
    out_sw_hb Decimal(10,4) COMMENT '当月漫出天数与上月相比的环比变化比例',
    roam_counts Int32 COMMENT '用户当月漫游通话次数',
    inent_call_counts Int32 COMMENT '用户当月VPMN（虚拟专用移动网）网内通话次数',
    inent_call_counts_v Decimal(10,4) COMMENT '当月VPMN网内通话次数与上月相比的增长比例',
    inent_call_duration_m Int64 COMMENT '用户当月VPMN网内通话时长',
    inent_call_duration_m_v Decimal(10,4) COMMENT '当月VPMN网内通话时长与上月相比的增长比例',
    is_jt Int8 COMMENT '判断用户是否为集团用户',
    is_jt_vpn Int8 COMMENT '判断用户是否为集团V网用户',
    is_jt_key_cust Int8 COMMENT '判断用户是否为集团关键人',
    jtyd_3month Int8 COMMENT '此用户跟三月前比是否取消集团用户、集团V网、集团关键人',
    innet_jt_time Date COMMENT '用户加入集团的时间',
    kd_3month Int8 COMMENT '判断用户近3个月是否为宽带用户',
    kd_cj_month Int8 COMMENT '判断用户当月是否拆除了宽带服务',
    kd_cj_3month Int8 COMMENT '判断用户近3个月是否拆除了宽带服务',
    kd_expire_date Date COMMENT '用户宽带服务的到期时间',
    kd_user_mark Int8 COMMENT '判断用户是否为家庭宽带客户',
    ywkd_user_mark Int8 COMMENT '判断用户是否为异网宽带客户',
    if_local_kdcover Int8 COMMENT '同此用户统一居住地用户无任何办理宽带用户则认为无宽带覆盖（若有现成字段更好）',
    if_no_kdcover_bl Int8 COMMENT '非宽带用户且"用户居住地是否宽带覆盖"=0',
    if_kd_poor Int8 COMMENT '近期存在掉线',
    kd_bl_times Int32 COMMENT '宽带办理时间计算',
    prod_bandwidth String COMMENT '用户宽带的带宽（速率）',
    mtd_flow Int64 COMMENT '用户当月宽带累计流量',
    mtd_flow_pre1 Int64 COMMENT '用户上月宽带累计流量',
    mtd_flow_pre2 Int64 COMMENT '用户上上月宽带累计流量',
    mtd_flow_bd Decimal(10,4) COMMENT '用户宽带流量的波动情况',
    is_fuse Int8 COMMENT '判断用户是否参与了捆绑活动',
    kb_eff_times Int32 COMMENT '捆绑活动的生效时长',
    kb_exp_times Int32 COMMENT '捆绑活动的剩余时长',
    assure_fee Decimal(18,2) COMMENT '用户宽带押金金额',
    is_0_flow Int8 COMMENT '判断用户当月是否为宽带零流量用户',
    is_renew Int8 COMMENT '判断用户当月是否续期了宽带服务',
    is_mbh Int8 COMMENT '判断用户是否使用魔百和服务',
    is_group Int8 COMMENT '判断用户是否使用小微宽带服务',
    mtd_active_day Int32 COMMENT '用户当月宽带累计活跃天数',
    mtd_active_day_pre1 Int32 COMMENT '用户上月宽带累计活跃天数',
    mtd_active_day_pre2 Int32 COMMENT '用户上上月宽带累计活跃天数',
    mtd_active_day_hb Decimal(10,4) COMMENT '当月累计活跃天数与上月相比的环比变化比例',
    mtd_active_day_bd Decimal(10,4) COMMENT '用户宽带累计活跃天数的波动情况',
    mtd_time_length Int64 COMMENT '用户当月宽带累计活跃时长',
    mtd_time_length_pre1 Int64 COMMENT '用户上月宽带累计活跃时长',
    mtd_time_length_pre2 Int64 COMMENT '用户上上月宽带累计活跃时长',
    mtd_time_length_hb Decimal(10,4) COMMENT '当月累计活跃时长与上月相比的环比变化比例',
    mtd_time_length_bd Decimal(10,4) COMMENT '用户宽带累计活跃时长的波动情况',
    kd_fee Decimal(18,2) COMMENT '用户融合套餐中的宽带费用',
    zdxf_fee Decimal(18,2) COMMENT '用户融合套餐的最低消费金额',
    kb_promoeff_times Int32 COMMENT '融合活动的使用时长（单位：月）',
    kb_promoexp_times Int32 COMMENT '融合活动的剩余时长（单位：月）',
    is_jsb Int8 COMMENT '判断用户是否为宽带加速用户',
    is_box Int8 COMMENT '判断用户是否使用智能音箱',
    is_voicect Int8 COMMENT '判断用户是否适合使用智能遥控器',
    is_jt_yigr Int8 COMMENT '1.基于家庭成员表（位置和关系），本号码家庭ID下异网用户比例超过50%',
    is_jt_xc Int8 COMMENT '1.基于家庭成员表（位置和关系），本号码家庭ID下用户存在携出',
    is_jt_xccx Int8 COMMENT '发送携出查询是否满足条件短信',
    is_jt_xccg Int8 COMMENT '发送获取携出授权码短信',
    is_jt_kdcj Int8 COMMENT '家庭成员近3个月解除了宽带服务',
    is_jt_kdywxz Int8 COMMENT '家庭成员近3个月新增了异网宽带',
    pro_kind_contract Int8 COMMENT '用户是否签订了实物合约（如终端合约）',
    pro_mbcharge_contract Int8 COMMENT '用户是否签订了话费合约',
    pro_res_hold_month Int32 COMMENT '用户合约的总时长',
    is_heyue Int8 COMMENT '判断用户是否为合约用户',
    hy_dq_3month Int8 COMMENT '取近是三个月存在"是否合约用户"=0的 用户和三个月前月表"是否合约用户"=1',
    hy_sy_times Int32 COMMENT '用户合约的剩余时长',
    pro_term_contract Int8 COMMENT '用户是否签订了终端合约',
    is_heyuedaoqi Int8 COMMENT '判断用户合约是否在未来6个月内到期',
    is_dx Int8 COMMENT '判断用户是否参与了承诺低消活动',
    dx_lj_times Int32 COMMENT '低消捆绑活动的累计时长',
    dx_sy_times Int32 COMMENT '低消捆绑活动的剩余时长',
    bhd_month Decimal(10,4) COMMENT '用户当月低消使用量占承诺低消的比例',
    join_hd_month Int8 COMMENT '包含：绑定终端、促销产品、程控业务、中心业务、实物产品、有价卡、其他类促销活动',
    join_new_offer_month Int8 COMMENT '判断用户当月是否参与了新增促销活动',
    dg_ll_offer_month Int8 COMMENT '判断用户当月是否办理了流量活动',
    join_new_offer_3month Int8 COMMENT '判断用户近3个月是否参与了新增促销活动',
    dg_ll_offer_3month Int8 COMMENT '判断用户近3个月是否办理了流量活动',
    hy_never_users Int8 COMMENT '判断用户是否从未参与过合约活动',
    hy_repeat_users Int8 COMMENT '判断用户是否多次参与合约活动',
    unsub_bundle_cnt_month Int32 COMMENT '用户当月退订捆绑业务的次数',
    unsub_bundle_cnt_3month Int32 COMMENT '用户近3个月退订捆绑业务的次数',
    bundle_prepay_expire_duration Int32 COMMENT '捆绑预存话费的到期时长',
    bundle_gift_expire_duration Int32 COMMENT '捆绑赠机的到期时长',
    contract_expire_3month Int8 COMMENT '判断用户合约是否在未来3个月内到期',
    no_contract_activity_3month Int8 COMMENT '近三个月进行活动营销（活动营销表）均未办理',
    has_contract_activity_3month Int8 COMMENT '近三个月参与了活动营销（活动营销表）',
    port_restrict_user Int8 COMMENT '看看有没有标签',
    churn_restrict_user Int8 COMMENT '是否离网限制用户（晨哥给过表）',
    realname_user Int8 COMMENT '判断用户是否已完成实名认证',
    vice_card_user Int8 COMMENT '判断用户是否拥有副卡',
    refund_user Int8 COMMENT '判断用户是否享受返费优惠',
    refund_remain_months Int32 COMMENT '返费活动的剩余时长',
    query_port_sms_6month Int8 COMMENT '判断用户近6个月是否发送过查询携号转网资格的短信',
    query_port_sms_cnt_6month Int32 COMMENT '用户近6个月发送查询携号转网资格短信的次数',
    apply_port_3month Int8 COMMENT '判断用户近3个月是否申请过携出',
    cancel_broadband_3month Int8 COMMENT '判断用户近3个月是否解除了宽带服务',
    unbind_bank_alipay_wechat Int8 COMMENT '上月支付宝、微信活跃本月无活跃记录',
    wechat_alipay_use_down Int8 COMMENT '使用天数环比降低80%',
    address_change Int8 COMMENT '上月跟本月居住地不同',
    new_broadband_other_this Int8 COMMENT '判断用户当月是否新增了异网宽带',
    new_broadband_other_3month Int8 COMMENT '判断用户近3个月是否新增了异网宽带',
    call_10086_port Int8 COMMENT '客服电话类型中是否有携转相关类型',
    sms_port_query_this Int8 COMMENT '发送携出查询是否满足条件短信',
    apply_port_this Int8 COMMENT '发送获取携出授权码短信',
    sms_port_query_3month Int8 COMMENT '发送携出查询是否满足条件短信',
    apply_port_3month_again Int8 COMMENT '发送获取携出授权码短信',
    web_search_port Int8 COMMENT '判断用户是否通过网页搜索了携转政策',
    is_ts Int8 COMMENT '判断用户近1个月是否有投诉记录',
    ts_counts_m Int32 COMMENT '用户近1个月的投诉次数',
    ts_counts_3month Int32 COMMENT '用户近3个月的投诉次数',
    out_opposite_regular_count Int32 COMMENT '用户呼叫竞争对手客户的数量',
    yw_call_nums Int32 COMMENT '用户与异网用户通话的数量',
    yw_call_opp_counts Int32 COMMENT '用户异网交往圈的人数',
    yw_call_opp_counts_v Decimal(10,4) COMMENT '异网交往圈人数/交往圈总人数',
    yw_in_call_counts Int32 COMMENT '用户与异网用户的主叫通话次数',
    yw_in_call_high Int8 COMMENT '月异网通话次数占比大于35% 或者 月异网通话时长占比大于35%',
    p1_yw_in_call_counts_momr Decimal(10,4) COMMENT '本月与异网主叫通话次数与上月相比的环比变化比例',
    p2_yw_in_call_counts_momr Decimal(10,4) COMMENT '上月与异网主叫通话次数与上上月相比的环比变化比例',
    yw_in_call_duration Int64 COMMENT '用户与异网用户的主叫通话时长',
    p1_yw_in_call_duration_momr Decimal(10,4) COMMENT '本月与异网主叫通话时长与上月相比的环比变化比例',
    p2_yw_in_call_duration_momr Decimal(10,4) COMMENT '上月与异网主叫通话时长与上上月相比的环比变化比例',
    p1_yw_call_nums_momr Decimal(10,4) COMMENT '本月与异网主叫通话用户数与上月相比的环比变化比例',
    p2_yw_call_nums_momr Decimal(10,4) COMMENT '上月与异网主叫通话用户数与上上月相比的环比变化比例',
    CALLfw_kf_count Int32 COMMENT '用户主叫异网客服号码的次数（单位：次）',
    prv1_callin_ywkf_cnts Int32 COMMENT '用户上月主叫异网客服号码的次数',
    call_1001_counts Int32 COMMENT '用户当月主动呼叫联通客服10010的次数',
    p2_call10010_counts_momr Decimal(10,4) COMMENT '上月拨打联通客服与上上月相比的环比变化比例',
    p3_call10000_counts_momr Decimal(10,4) COMMENT '上上月拨打电信客服与前三月相比的环比变化比例',
    is_ts_high Int8 COMMENT '近3月投诉次数大于2，且有投诉升级记录，投诉解决率小于80%',
    is_tsjj_low Int8 COMMENT '解决率低于60%',
    call_1860_1861_counts Int32 COMMENT '用户当月主叫10086的通话次数',
    call_1860_1861_counts_v Decimal(10,4) COMMENT '当月主叫10086通话次数与上月相比的增长比例',
    call_1860_1861_duration_m Int64 COMMENT '用户当月主叫10086的通话时长',
    call_1860_1861_duration_m_v Decimal(10,4) COMMENT '当月主叫10086通话时长与上月相比的增长比例',
    wx_cnt_month Int32 COMMENT '用户当月使用微信的频次',
    wx_days_month Int32 COMMENT '用户当月使用微信的天数',
    prv1_wx_cnt Int32 COMMENT '用户上月使用微信的频次',
    prv1_wx_days Int32 COMMENT '用户上月使用微信的天数',
    prv2_wx_cnt Int32 COMMENT '用户上上月使用微信的频次',
    prv2_wx_days Int32 COMMENT '用户上上月使用微信的天数',
    bank_num_month Int32 COMMENT '用户当月使用的银行APP数量',
    prv1_bank_num Int32 COMMENT '用户上月使用的银行APP数量',
    prv2_bank_num Int32 COMMENT '用户上上月使用的银行APP数量',
    bank_cnt_month Int32 COMMENT '用户当月使用银行APP的频次',
    prv1_bank_cnt Int32 COMMENT '用户上月使用银行APP的频次',
    prv2_bank_cnt Int32 COMMENT '用户上上月使用银行APP的频次',
    jiaz_wending_rate Decimal(10,4) COMMENT '近3个月收入标准差/近3个月收入平均数',
    gprs_wending_rate Decimal(10,4) COMMENT '近3个月通用流量标准差/近3个月通用流量平均数',
    is_zifee_mg Int8 COMMENT '口径:近6个月更换套餐2次以上或主动退订业务4次以上',
    is_busi_td Int8 COMMENT '近6个月主动退订流量包2次以上',
    ts_fee Int8 COMMENT '投诉或升级投诉话单中投诉内容存在费用质疑',
    network_signal_unsatisfied Int8 COMMENT '当月产生过2G流量或当月检测到4G-2G网络切换标识',
    internet_slow Int8 COMMENT '宽带用户且近3月投诉过宽带网络或资费',
    signal_quality_poor Int8 COMMENT '是否MR弱覆盖',
    call_drop Int8 COMMENT '存在通话掉话',
    double_decline Int8 COMMENT '当月相比前三月DOU、ARPU均下降30% 或 当月相比去年末DOU、ARPU均下降30%',
    quasi_churn Int8 COMMENT '预销或者停机达到5天',
    account_pre_churn Int8 COMMENT '用户状态是116、126方可转变账务预销户3',
    business_pre_churn Int8 COMMENT '用户状态是3,100,103,114,115,116,126,131均可转变为营业预销:2',
    voice_use_users Int32 COMMENT '成功办理客户中产生语音的用户数',
    voice_saturation Decimal(10,4) COMMENT '套餐及语音包饱和度',
    low_call_ratio Decimal(10,4) COMMENT '成功办理客户中使用语音少于10分钟的用户占比',
    data_use_users Int32 COMMENT '成功办理客户中产生流量的用户数',
    general_data_saturation Decimal(10,4) COMMENT '套餐及通用流量包饱和度（含结转流量）',
    low_data_ratio Decimal(10,4) COMMENT '成功办理客户中使用流量少于300M 的用户占比',
    roam_type String COMMENT '漫游客户(常漫/长漫)',
    overdue_stop Int8 COMMENT '到预销户时间可先按30算，这块比交复杂，地市自己可以配置',
    double_stop Int8 COMMENT '套餐不同欠费到停机机制也不同，这块的逻辑是：信誉度没了后再欠费x元进单停，再欠费y元进；如果没有单双停机制的套餐，就是信誉度没了再欠z元就双停或者叫停机了',
    single_stop Int8 COMMENT '可以接打任意电话，双停只能拨打10086，不能接听来自86的电话（其实也意义不大了），预销户开始就彻底失连了'
) ENGINE = MergeTree ORDER BY (month)
COMMENT '用户行为特征表';
    """
    
    ddl_strategies = """
    -- 创建策略表（存储运营策略及历史效果）
    CREATE TABLE IF NOT EXISTS strategies (
    id SERIAL PRIMARY KEY,   --策略ID
    name VARCHAR(200) NOT NULL,                     -- 策略名称
    category VARCHAR(50),                           -- 策略类别：挽留/交叉销售/升级/激活
    description TEXT,                               -- 策略详细描述
    product_ids VARCHAR(500),                       -- 关联的产品ID列表，逗号分隔
    conditions TEXT,                                -- 适用条件（如 ARPU>100）
    channel_preference VARCHAR(50),                 -- 推荐渠道（短信/APP推送/邮件等）
    discount_ratio FLOAT,                           -- 优惠折扣比例（0~1）
    avg_conversion_rate FLOAT DEFAULT 0,            -- 历史平均转化率（0~1）
    avg_roi FLOAT DEFAULT 0,                        -- 历史平均ROI（投资回报率）
    avg_click_rate FLOAT DEFAULT 0,                 -- 历史平均点击率/接通率（0~1）
    sample_count INT DEFAULT 0,                     -- 样本数量（用于统计置信度）
    is_active BOOLEAN DEFAULT TRUE,                 -- 是否启用
    created_at TIMESTAMPTZ DEFAULT NOW(),           -- 创建时间
    updated_at TIMESTAMPTZ                          -- 更新时间
);
    """
    
    ddl_products = """
    -- 创建产品表（存储可供营销的产品，依据通信行业分类）
CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,  --产品ID
    name VARCHAR(200) NOT NULL,                     -- 产品名称
    category VARCHAR(50),                           -- 一级分类：个人套餐/语音包/流量包/数字化权益/家庭宽带/硬件/集团业务等
    sub_category VARCHAR(50),                       -- 二级分类：如咪咕视频、移动云盘、智能组网等
    price FLOAT,                                    -- 售价（元）
    original_price FLOAT,                           -- 原价（元）
    discount_supported BOOLEAN DEFAULT TRUE,        -- 是否支持优惠
    description TEXT,                               -- 产品描述
    target_user_type VARCHAR(50),                   -- 目标用户类型：高流量/低流量/新用户/老用户/家庭/企业
    -- 通信行业特有字段
    package_size VARCHAR(50),                       -- 套餐包大小（如：5GB、100分钟、200条）
    valid_period VARCHAR(50),                       -- 有效期（如：当月有效、7天、长期）
    applicable_scope VARCHAR(100),                  -- 适用范围（如：全国、省内、定向APP）
    is_active BOOLEAN DEFAULT TRUE,                 -- 是否上架
    created_at TIMESTAMPTZ DEFAULT NOW()            -- 创建时间
);
    """
    
    ddl_scripts = """
    -- 创建话术库表
CREATE TABLE IF NOT EXISTS scripts (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,                         -- 话术内容
    scenario VARCHAR(100),                         -- 适用场景（如流量超套挽留）
    product_id INT,                                 -- 关联产品ID
    strategy_id INT,                                -- 关联策略ID
    user_segment VARCHAR(50),                      -- 适用用户分群
    channel VARCHAR(50),                           -- 推荐渠道
    compliance_status VARCHAR(20) DEFAULT 'approved', -- 合规状态
    usage_count INT DEFAULT 0,                     -- 使用次数
    avg_ctr FLOAT DEFAULT 0,                       -- 历史平均点击率
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);
    """
    
    ddl_execution_plans = """
    -- 执行计划表（存储历史运营执行配置及效果，用于推荐）
CREATE TABLE IF NOT EXISTS execution_plans (
    id SERIAL PRIMARY KEY,
    strategy_id INT,                                -- 关联策略ID
    audience_segment VARCHAR(100),                  -- 客群分群描述
    channel VARCHAR(50),                            -- 推荐渠道（APP/短信/外呼等）
    wave_count INT DEFAULT 1,                       -- 波次数量
    wave_interval_hours INT,                        -- 波次间隔（小时）
    send_time_preference VARCHAR(50),               -- 时刻偏好（如：晚间、上午、个性化）
    actual_conversion_rate FLOAT,                   -- 实际转化率
    actual_roi FLOAT,                               -- 实际ROI
    usage_count INT DEFAULT 0,                      -- 使用次数
    created_at TIMESTAMPTZ DEFAULT NOW()
);
    """
    
    # 训练 DDL
    logger.info("开始训练 DDL...")
    for name, ddl in [("user_behavior", ddl_user_behavior), ("strategies", ddl_strategies),
                      ("products", ddl_products), ("scripts", ddl_scripts),
                      ("execution_plans", ddl_execution_plans)]:
        try:
            vn.train(ddl=ddl)
            logger.info(f"训练 DDL 成功: {name}")
        except Exception as e:
            logger.error(f"训练 DDL {name} 失败: {e}", exc_info=True)
    
    # ========== 训练业务文档 ==========
    # 请将您的完整 docs 列表粘贴在这里（此处仅示例几条）
    docs = [
        "近12个月主叫通话时长:近12个月主叫通话时长",
        "近1个月流量:近1个月流量",
        "近1个月收入:近1个月收入",
        "近1个月主叫通话时长:近1个月主叫通话时长",
        "近2个月流量:近2个月流量",
        "近2个月收入:近2个月收入",
        "近2个月主叫通话时长:近2个月主叫通话时长",
        "近3个月流量:近3个月流量",
        "近3个月收入:近3个月收入",
        "近3个月主叫通话时长:近3个月主叫通话时长",
        "近4个月流量:近4个月流量",
        "近4个月收入:近4个月收入",
        "近4个月主叫通话时长:近4个月主叫通话时长",
        "近5个月流量:近5个月流量",
        "近5个月收入:近5个月收入",
        "近5个月主叫通话时长:近5个月主叫通话时长",
        "近6个月流量:近6个月流量",
        "近6个月收入:近6个月收入",
        "近6个月主叫通话时长:近6个月主叫通话时长",
        "近7个月流量:近7个月流量",
        "近7个月收入:近7个月收入",
        "近7个月主叫通话时长:近7个月主叫通话时长",
        "近8个月流量:近8个月流量",
        "近8个月收入:近8个月收入",
        "近8个月主叫通话时长:近8个月主叫通话时长",
        "近9个月流量:近9个月流量",
        "近9个月收入:近9个月收入",
        "近9个月主叫通话时长:近9个月主叫通话时长",
        "是否潜在换机用户:依据换机频率标签",
        "最佳匹配推荐终端型号:根据模型结合卓越100机型及CRM集约机型选取获得",
        "最佳匹配推荐终端5位码:根据模型结合卓越100机型及CRM集约机型选取获得",
        "同价位推荐终端型号:根据模型结合卓越100机型及CRM集约机型选取获得",
        "同价位推荐终端5位码:根据模型结合卓越100机型及CRM集约机型选取获得",
        "升档匹配推荐终端型号:根据模型结合卓越100机型及CRM集约机型选取获得",
        "升档匹配推荐终端5位码:根据模型结合卓越100机型及CRM集约机型选取获得",
        "最佳匹配推荐终端品牌:根据模型结合卓越100机型及CRM集约机型选取获得",
        "同价位推荐终端品牌:根据模型结合卓越100机型及CRM集约机型选取获得",
        "升档匹配推荐终端品牌:根据模型结合卓越100机型及CRM集约机型选取获得",
        "潜在3升4终端用户:1)是否开通4G功能=否 且三个月内更换过终端=是2）是否开通4G功能=否 且三个月内更换过终端=否 且入网时长 >24(月) 且三月内月均呼出次数 > 58.33(次) 且三个月平均语音饱和度 < 0.7 且是否使用4G套餐=是",
        "潜在七天流量包营销用户:根据历史7天包订购情况和流量使用情况判断潜在的营销用户",
        "潜在三天流量包营销用户:根据历史3天包订购情况和流量使用情况判断潜在的营销用户",
        "潜在视频流量包营销用户:根据历史订购流量包和加餐包情况和流量使用情况判断潜在的营销用户",
        "潜在闲时流量包营销用户:根据历史订购流量包和加餐包情况和流量使用情况判断潜在的营销用户",
        "潜在一天流量包营销用户:根据历史1天包订购情况和流量使用情况判断潜在的营销用户",
        "身份属性:征信类得分",
        "行为偏好:征信类得分",
        "历史信用:征信类得分",
        "社交关系:征信类得分",
        "橙信分:征信类得分",
        "政治偏好度:识别用户使用手机的上网兴趣偏好",
        "阅读偏好度:识别用户使用手机的上网兴趣偏好",
        "百科全书偏好度:识别用户使用手机的上网兴趣偏好",
        "报刊杂志偏好度:识别用户使用手机的上网兴趣偏好",
        "计划方案偏好度:识别用户使用手机的上网兴趣偏好",
        "经济管理偏好度:识别用户使用手机的上网兴趣偏好",
        "居家生活偏好度:识别用户使用手机的上网兴趣偏好",
        "科学技术偏好度:识别用户使用手机的上网兴趣偏好",
        "励志成功偏好度:识别用户使用手机的上网兴趣偏好",
        "漫画偏好度:识别用户使用手机的上网兴趣偏好",
        "求职职场偏好度:识别用户使用手机的上网兴趣偏好",
        "人文社科偏好度:识别用户使用手机的上网兴趣偏好",
        "少儿天地偏好度:识别用户使用手机的上网兴趣偏好",
        "家庭圈存在异网号码用户:通过家庭圈标签找出同一家庭的多个用户，分别判断用户是否为异网号码。如有异网号码存在，则判定为家庭圈存在异网号码用户。",
        "5g倾向度:使用熵值法模型，输入用户电信业务特征标签值，进行打分，根据打分结果计算用户得分均值和均方差划分用户档位，形成5g高/中/低倾向。",
        "5g潜在用户价值:根据5g倾向度标签值，分别将高、中价值用户通过K-means模型聚类，得到分类结果，分析各类用户特征，得出对应用户价值。",
        "客户入网时间:客户入网时间",
        "是否单C:客户名下没有固话/宽带/itv产品的用户",
        "副卡数量:主卡用户对应客户名下，对应的副卡数量",
        "沉默副卡数量:沉默副卡数量，无短信、无语音、无流量则为沉默",
        "入网时间:客户入网时间",
        "在网时长(月):判断用户开通时间距离当月账期的时长",
        "是否是不限量用户:基于销售品信息，判断用户是否为不限量套餐用户",
        "三月内月均使用流量（M）:取用户三个月内使用流量的均值，单位M",
        "本月优惠后用户收入(元):本月优惠后用户收入(元)",
        "是否互联网卡用户:基于互联网卡用户清单，判断用户是否为互联网卡用户",
        "是否是5G预约用户:预约5G套餐用户",
        "是否5G异网预约用户:预约5G套餐的异网用户",
        "迁转5g目标客户:1-A1：高风险区-流量[0,5)G,出账金额129以上融合，融合用户, 2-A2：高风险区-流量[5,30)G,出账金额169以上融合，融合用户,3-B2：价值提升区-流量[5,30)G,出账金额79-299区间1,4-B3：价值提升区-流量30G以上,出账金额79-299区间2,5-C2：流量激发区-流量[5,30)G,出账金额229以下。",
        "客户名下出账移动用户数:客户名下出账移动用户数",
        "流量高饱和用户:所用流量超过订购流量和的70%",
        "捆绑中低带宽用户:是否200M及以下宽带",
        "潜在5g终端用户:有5G倾向度的客户",
        "集团电渠权益产品（停复机专用）:以集团电渠停复机对应的销售品为准，频率为日。",
        "5G会员销售品名称:订购了ppm销售品属性（200010000027)为1002：会员 的销售品，即为5G会员。",
        "5G权益销售品名称:订购了ppm销售品属性（200010000027)为1007：生态权益或1008 ：应用权益 的销售品，即为5G权益用户。省份自建。",
        "外语学习偏好度:识别用户使用手机的上网兴趣偏好",
        "文学经典偏好度:识别用户使用手机的上网兴趣偏好",
        "学术论文偏好度:识别用户使用手机的上网兴趣偏好",
        "研究生考试偏好度:识别用户使用手机的上网兴趣偏好",
        "艺术摄影偏好度:识别用户使用手机的上网兴趣偏好",
        "有声读物偏好度:识别用户使用手机的上网兴趣偏好",
        "资格考试偏好度:识别用户使用手机的上网兴趣偏好",
        "游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "策略游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "单机游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "动作偏好度:识别用户使用手机的上网兴趣偏好",
        "格斗游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "角色扮演偏好度:识别用户使用手机的上网兴趣偏好",
        "竞速游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "卡牌游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "冒险偏好度:识别用户使用手机的上网兴趣偏好",
        "模拟经营偏好度:识别用户使用手机的上网兴趣偏好",
        "跑酷类偏好度:识别用户使用手机的上网兴趣偏好",
        "棋牌游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "赛车游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "射击飞行偏好度:识别用户使用手机的上网兴趣偏好",
        "体育竞技偏好度:识别用户使用手机的上网兴趣偏好",
        "网络游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "页面游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "益智休闲偏好度:识别用户使用手机的上网兴趣偏好",
        "音乐游戏偏好度:识别用户使用手机的上网兴趣偏好",
        "音乐偏好度:识别用户使用手机的上网兴趣偏好",
        "八卦消息偏好度:识别用户使用手机的上网兴趣偏好",
        "明星资讯偏好度:识别用户使用手机的上网兴趣偏好",
        "社交偏好度:识别用户使用手机的上网兴趣偏好",
        "影视资讯偏好度:识别用户使用手机的上网兴趣偏好",
        "娱乐时尚偏好度:识别用户使用手机的上网兴趣偏好",
        "体育偏好偏好度:识别用户使用手机的上网兴趣偏好",
        "视频偏好度:识别用户使用手机的上网兴趣偏好",
        "财经偏好度:识别用户使用手机的上网兴趣偏好",
        "电视剧偏好度:识别用户使用手机的上网兴趣偏好",
        "电影偏好度:识别用户使用手机的上网兴趣偏好",
        "动漫偏好度:识别用户使用手机的上网兴趣偏好",
        "体育偏好度:识别用户使用手机的上网兴趣偏好",
        "微电影偏好度:识别用户使用手机的上网兴趣偏好",
        "戏曲偏好度:识别用户使用手机的上网兴趣偏好",
        "资讯偏好度:识别用户使用手机的上网兴趣偏好",
        "综艺偏好度:识别用户使用手机的上网兴趣偏好",
        "教育偏好度:识别用户使用手机的上网兴趣偏好",
        "购物偏好度:识别用户使用手机的上网兴趣偏好",
        "母婴市场偏好度:识别用户使用手机的上网兴趣偏好",
        "财经资讯偏好度:识别用户使用手机的上网兴趣偏好",
        "家庭类型:识别用户的家庭类型特征",
        "社会分群:识别用户的社会分群特征",
        "职业标签:识别用户的职业特征",
        "注智-换机频率偏好:基于用户历史终端轨迹，3年内换机次数>=2且剔除使用终端小于7天的。为高，否则为低。",
        "注智-终端类型偏好:追溯用户自入网起的有效换机行为下，依据是用户的终端价格偏好，结合其近6个月平均ARPU，判定",
        "注智-偏好终端品牌:追溯用户自入网起或有终端历史信息起，有效的换机行下，换机次数最多的品牌",
        "注智-终端品牌偏好:追溯用户近三年内的有效换机行为下，依据是当前使用终端的品牌且拥有较长的持机时长",
        "注智-消费潜力:近6个月的平均出账收入，不足6个月，按在网时间算",
        "流量使用偏好:识别用户的流量使用特征",
        "是否视频偏好:识别用户的视频偏好特征",
        "手机上网偏好:识别用户使用手机的上网兴趣偏好",
        "注智-渠道偏好:用户发展渠道",
        "注智-离网倾向:近三个月arup降低，且合约到期时间-当前时间<3",
        "注智-业务偏好:用户潜在营销业务场景",
        "注智-服务信息:投诉类型",
        "APP偏好top1:识别用户使用APP排名",
        "APP偏好top1（当月访问次数）:识别用户top1APP使用次数",
        "APP偏好top1（当月使用流量）:识别用户top1APP使用流量",
        "APP偏好top1（当月访问天数）:识别用户top1APP使用天数",
        "APP偏好top2:识别用户使用APP排名",
        "APP偏好top2（当月访问次数）:识别用户top2APP使用次数",
        "APP偏好top2（当月使用流量）:识别用户top2APP使用流量",
        "APP偏好top2（当月访问天数）:识别用户top2APP使用天数",
        "APP偏好top3:识别用户使用APP排名",
        "APP偏好top3（当月访问次数）:识别用户top3APP使用次数",
        "APP偏好top3（当月使用流量）:识别用户top3APP使用流量",
        "APP偏好top3（当月访问天数）:识别用户top3APP使用天数",
        "APP偏好top4:识别用户使用APP排名",
        "APP偏好top4（当月访问次数）:识别用户top4APP使用次数",
        "APP偏好top4（当月使用流量）:识别用户top4APP使用流量",
        "APP偏好top4（当月访问天数）:识别用户top4APP使用天数",
        "APP偏好top5:识别用户使用APP排名",
        "APP偏好top5（当月访问次数）:识别用户top5APP使用次数",
        "APP偏好top5（当月使用流量）:识别用户top5APP使用流量",
        "APP偏好top5（当月访问天数）:识别用户top5APP使用天数",
        "开通时间:用户入网时间",
        "拆机时间:用户拆机时间",
        "产品实例状态:产品实例中间层表-产品实例状态",
        "年龄:根据身份证号码测算年龄",
        "性别:根据身份证号码测算性别",
        "是否计费\出账到达（集团）:产品实例中间层表-产品实例状态",
        "上月是否计费\出账到达（集团）:产品实例中间层表-产品实例状态",
        "是否在网\网上到达:是否在用或停机",
        "互联网卡短编码:用户办理互联网卡销售品的短编码",
        "互联网卡长编码:用户办理互联网卡销售品的长编码",
        "互联网卡类型:判断用户办理的互联网卡类型",
        "米粉体验卡短编码:用户办理的米粉体验卡销售品短编码",
        "米粉体验卡长编码:用户办理的米粉体验卡销售品长编码",
        "米粉体验卡类型:判断用户办理的米粉体验卡类型",
        "互联网卡销售品竣工时间:判断用户办理的互联网卡销售品竣工时间",
        "终端价格（上市价格）:取用户当前使用终端上市的价格",
        "主叫计费时长:统计用户主叫的计费时长",
        "点对点短信条数（本月短信数）:统计用户点对点条数数量",
        "客户拥有移动电话产品数:统计用户名下拥有移动产品个数",
        "是否集约渠道:基于集约渠道码表，判断用户是否来自集约渠道",
        "是否小白:基于互联网卡用户清单，判断用户是否为小白用户",
        "是否首充:基于互联网卡用户清单，判断用户是否为首冲用户",
        "客户拥有固话产品数:统计客户名下拥有固话产品的个数",
        "客户拥有宽带产品数:统计客户名下拥有宽带产品的个数",
        "客户拥有ITV产品数:统计客户名下拥有ITV产品的个数",
        "是否活跃用户:活跃口径： 1、移动产品，通话时长>0 或者 手机上网流量>0 或者 短信（手机点对点短信数 或 手机SP短信发送条数/SP上行(增值话单)）>0；2、固话产品，通话时长>0 ；3、ITV活跃标(开机次数 或者 收视时长>0为活跃)；4、宽带产品：上网时长 >0 或者 上网流量>0。】(以上4条满足任一条件，即为活跃用户)",
        "是否低效用户:低效口径：（通话时长+短信+手机上网流量 ）小于30 的。(不区分产品类型)",
        "本月欠费金额(元):统计用户当月的欠费金额",
        "欠费总金额(元):统计用户欠费总金额",
        "上月优惠前用户收入(元):取T-1月赠款冲减前的用户税后收入",
        "上上月优惠前用户收入(元):取T-2月赠款冲减前的用户税后收入",
        "三月内月均呼出次数:取用户三个月内月均呼出次数",
        "三月内月均主叫计费时长:取用户三个月均主叫计费时长",
        "是否音乐偏好:根据用户当月APP使用情况，判断用户是否为音乐偏好用户",
        "是否炒股偏好:根据用户当月APP使用情况，判断用户是否为炒股偏好用户",
        "渠道大类:判断在网用户渠道大类：实体渠道，电子渠道，政企渠道，未知渠道",
        "渠道小类:判断在网用户渠道小类：行业客户直销经理、商业客户直销经理、校园客户直销经理、行业客户直销代理、商业客户直销代理、校园客户直销代理、公众直销经理等46个小类",
        "新终端尝鲜族:筛选终端使用条件为近三年换过新终端，且新终端上市时间<半年，且最新终端与最近注册终端不一致或者终端一致但售价>5000或者现终端无法匹配的在用用户。",
        "疑似家装异网宽带用户:通过用户日间流量与夜间流量比值、是否订购宽带产品等信息，分析用户是否为疑似家装异网宽带用户。",
        "家庭构成-二人世界:识别用户家庭的构成情况",
        "家庭构成-三口之家:识别用户家庭的构成情况",
        "家庭构成-未知:识别用户家庭的构成情况",
        "家庭特征-家有儿童:识别用户家庭的特征情况",
        "家庭特征-家有老人:识别用户家庭的特征情况",
        "家庭特征-未知:识别用户家庭的特征情况",
        "出国人群:识别用户是否经常出国",
        "年龄（基于用户行为）:识别用户的年龄信息",
        "视频使用分群:识别用户的视频分群特征",
        "外来务工:识别用户是否为外来务工人员（户口所在地与工作地城市不同）",
        "王者荣耀重度玩家:识别用户是否为王者荣耀重度玩家",
        "性别（基于用户行为）:识别用户的性别",
        "学生群体:识别用户是否为学生（目前仅包括本科生、研究生和博士生）",
        "孕婴人群:识别用户是否为孕妇或者有婴儿",
        "节假日换机偏好:基于历史终端注册时间与节假日重合次数>=2为高，1为中，没有为低。节假日已加入电商节。",
        "类型偏好-追新型:根据首次终端注册时间判断",
        "类型偏好-低端型:追溯用户自入网起的有效换机行为下，依据是用户的终端价格偏好，结合其近6个月平均ARPU，判定其是否为低端型用户",
        "类型偏好-土豪型:追溯用户自入网起的有效换机行为下，依据是用户的终端价格偏好，结合其近6个月平均ARPU，判定其是否为土豪型用户",
        "类型偏好-面子型:追溯用户自入网起的有效换机行为下，依据是用户的终端价格偏好，结合其近6个月平均ARPU，判定",
        "类型偏好-节俭型:追溯用户自入网起的有效换机行为下，依据是用户的终端价格偏好，结合其近6个月平均ARPU，判定",
        "类型偏好-忠诚型:追溯用户近三年内的有效换机行为下，依据是某品牌手机并且拥有较长的持机时长",
        "偏好终端操作系统:追溯用户3年内的有效换机行为下，所持终端的操作系统，依据所使用的时间以及换机次数进行综合处理，判定用户对于终端操作系统的偏好",
        "品牌排序-偏好终端品牌TOP1:追溯用户自入网起或有终端历史信息起，有效的换机行下，换机次数最多的终端top1。",
        "品牌排序-偏好终端品牌TOP2:追溯用户自入网起或有终端历史信息起，有效的换机行下，换机次数最多的终端top2。",
        "品牌排序-偏好终端品牌TOP3:追溯用户自入网起或有终端历史信息起，有效的换机行下，换机次数最多的终端top3。",
        "是否升档用户:基于用户终端轨迹，上款终端的价格和当前的终端价格做对比。差值500元为是，否则为否。",
        "特定品牌偏好-三星粉:追溯用户近三年内的有效换机行为下，依据是否拥有多部三星手机并且拥有较长的持机时长，判定其是否为三星品牌偏好用户",
        "终端换机价格便好:基于用户历史终端的价格进行打标",
        "特定品牌偏好-果粉:追溯用户近三年内的有效换机行为下，依据是否拥有多部苹果手机并且拥有较长的持机时长，判定其是否为苹果品牌偏好用户",
        "特定品牌偏好-终端国产族:追溯用户自入网起的国产机使用次数以及持机时长，综合判定用户对于国产机的偏好",
        "特定品牌偏好-华为粉:追溯用户近三年内的有效换机行为下，依据是否拥有多部华为手机并且拥有较长的持机时长，判定其是否为华为品牌偏好用户",
        "特定品牌偏好-米粉:追溯用户近三年内的有效换机行为下，依据是否拥有多部小米手机并且拥有较长的持机时长，判定其是否为小米品牌偏好用户",
        "特定品牌偏好-oppo粉:追溯用户近三年内的有效换机行为下，依据是否拥有多部OPPO手机并且拥有较长的持机时长，判定其是否为OPPO品牌偏好用户",
        "特定品牌偏好-是否vivo粉:追溯用户近三年内的有效换机行为下，依据是否拥有多部VIVO手机并且拥有较长的持机时长，判定其是否为VIVO品牌偏好用户",
        "特定品牌偏好-追新果粉:溯用户自入网起的有效换机时间与终端上市时间的时间间隔，综合判定用户对于追求新款终端的品牌是苹果手机",
        "特定品牌偏好-务实果粉:用户在新苹果终端上市前3个月，购买上以苹果型号的终端",
        "终端主屏偏好:追溯用户3年内的有效换机行为下，所持终端的屏幕大小，依据所使用的时间进行加权均值处理，判定用户对于终端屏幕的偏好",
        "通话次数top1时段:识别用户的通话时段偏好（按次数排序）",
        "通话次数top2时段:识别用户的通话时段偏好（按次数排序）",
        "通话次数top3时段:识别用户的通话时段偏好（按次数排序）",
        "通话次数top4时段:识别用户的通话时段偏好（按次数排序）",
        "通话次数top5时段:识别用户的通话时段偏好（按次数排序）",
        "通话次数top6时段:识别用户的通话时段偏好（按次数排序）",
        "通话次数top7时段:识别用户的通话时段偏好（按次数排序）",
        "通话时长top1时段:识别用户的通话时段偏好（按时长排序）",
        "通话时长top2时段:识别用户的通话时段偏好（按时长排序）",
        "通话时长top3时段:识别用户的通话时段偏好（按时长排序）",
        "通话时长top4时段:识别用户的通话时段偏好（按时长排序）",
        "通话时长top5时段:识别用户的通话时段偏好（按时长排序）",
        "通话时长top6时段:识别用户的通话时段偏好（按时长排序）",
        "通话时长top7时段:识别用户的通话时段偏好（按时长排序）",
        "流量消耗TOP1时段:识别用户的上网时段偏好（按消耗流量排序）",
        "流量消耗TOP2时段:识别用户的上网时段偏好（按消耗流量排序）",
        "流量消耗TOP3时段:识别用户的上网时段偏好（按消耗流量排序）",
        "流量消耗TOP4时段:识别用户的上网时段偏好（按消耗流量排序）",
        "流量消耗TOP5时段:识别用户的上网时段偏好（按消耗流量排序）",
        "流量消耗TOP6时段:识别用户的上网时段偏好（按消耗流量排序）",
        "流量消耗TOP7时段:识别用户的上网时段偏好（按消耗流量排序）",
        "工作日白天-出现次数TOP1的经纬度:取用户在工作日期间8点-17点出现次数排名第一的经纬度",
        "工作日白天-出现次数TOP2的经纬度:取用户在工作日期间8点-17点出现次数排名第二的经纬度",
        "工作日白天-出现次数TOP3的经纬度:取用户在工作日期间8点-17点出现次数排名第三的经纬度",
        "工作日白天-出现次数TOP4的经纬度:取用户在工作日期间8点-17点出现次数排名第四的经纬度",
        "工作日白天-出现次数TOP5的经纬度:取用户在工作日期间8点-17点出现次数排名第五的经纬度",
        "工作日夜间-出现次数TOP1的经纬度:取用户在工作日（非节假日及周六日）期间0点-7点，22点-23出现次数排名第一的经纬度",
        "工作日夜间-出现次数TOP2的经纬度:取用户在工作日（非节假日及周六日）期间0点-7点，22点-23出现次数排名第二的经纬度",
        "工作日夜间-出现次数TOP3的经纬度:取用户在工作日（非节假日及周六日）期间0点-7点，22点-23出现次数排名第三的经纬度",
        "工作日夜间-出现次数TOP4的经纬度:取用户在工作日（非节假日及周六日）期间0点-7点，22点-23出现次数排名第四的经纬度",
        "工作日夜间-出现次数TOP5的经纬度:取用户在工作日（非节假日及周六日）期间0点-7点，22点-23出现次数排名第五的经纬度",
        "T10使用终端厂商:追溯用户近三年内的有效换机行为下，取T10次使用终端的厂商",
        "T10使用终端串号:追溯用户近三年内的有效换机行为下，取T10次使用终端的终端串号",
        "T10使用终端五位码:追溯用户近三年内的有效换机行为下，取T10次使用终端的五位码",
        "T10使用终端型号:追溯用户近三年内的有效换机行为下，取T10次使用终端型号",
        "T10使用终端注册时间:追溯用户近三年内的有效换机行为下，取T10次使用终端注册时间",
        "T1当前使用终端厂商:当前终端厂商",
        "T1当前使用终端串号:当前终端串号",
        "T1当前使用终端五位码:当前终端五位码",
        "T1当前使用终端型号:当前终端型号",
        "T1当前使用终端注册时间:当前终端注册时间",
        "T2上次使用终端厂商:追溯用户近三年内的有效换机行为下，取T2次使用终端厂商",
        "T2上次使用终端串号:追溯用户近三年内的有效换机行为下，取T2次使用终端的终端串号",
        "T2上次使用终端五位码:追溯用户近三年内的有效换机行为下，取T2次使用终端的五位码",
        "T2上次使用终端型号:追溯用户近三年内的有效换机行为下，取T2次使用终端型号",
        "T2上次使用终端注册时间:追溯用户近三年内的有效换机行为下，取T2次使用终端注册时间",
        "T3上上次使用终端厂商:追溯用户近三年内的有效换机行为下，取T23次使用终端厂商",
        "T3上上次使用终端串号:追溯用户近三年内的有效换机行为下，取T3次使用终端的终端串号",
        "T3上上次使用终端五位码:追溯用户近三年内的有效换机行为下，取T3次使用终端的五位码",
        "T3上上次使用终端型号:追溯用户近三年内的有效换机行为下，取T3次使用终端型号",
        "T3上上次使用终端注册时间:追溯用户近三年内的有效换机行为下，取T3次使用终端注册时间",
        "T4使用终端厂商:追溯用户近三年内的有效换机行为下，取T4次使用终端厂商",
        "T4使用终端串号:追溯用户近三年内的有效换机行为下，取T4次使用终端的终端串号",
        "T4使用终端五位码:追溯用户近三年内的有效换机行为下，取T4次使用终端的五位码",
        "T4使用终端型号:追溯用户近三年内的有效换机行为下，取T4次使用终端型号",
        "T4使用终端注册时间:追溯用户近三年内的有效换机行为下，取T4次使用终端注册时间",
        "T5使用终端厂商:追溯用户近三年内的有效换机行为下，取T5次使用终端厂商",
        "T5使用终端串号:追溯用户近三年内的有效换机行为下，取T5次使用终端的终端串号",
        "T5使用终端五位码:追溯用户近三年内的有效换机行为下，取T5次使用终端的五位码",
        "T5使用终端型号:追溯用户近三年内的有效换机行为下，取T5次使用终端型号",
        "T5使用终端注册时间:追溯用户近三年内的有效换机行为下，取T5次使用终端注册时间",
        "T6使用终端厂商:追溯用户近三年内的有效换机行为下，取T6次使用终端厂商",
        "T6使用终端串号:追溯用户近三年内的有效换机行为下，取T6次使用终端的终端串号",
        "T6使用终端五位码:追溯用户近三年内的有效换机行为下，取T6次使用终端的五位码",
        "T6使用终端型号:追溯用户近三年内的有效换机行为下，取T6次使用终端型号",
        "T6使用终端注册时间:追溯用户近三年内的有效换机行为下，取T6次使用终端注册时间",
        "T7使用终端厂商:追溯用户近三年内的有效换机行为下，取T7次使用终端厂商",
        "T7使用终端串号:追溯用户近三年内的有效换机行为下，取T7次使用终端的终端串号",
        "T7使用终端五位码:追溯用户近三年内的有效换机行为下，取T7次使用终端的五位码",
        "T7使用终端型号:追溯用户近三年内的有效换机行为下，取T7次使用终端型号",
        "T7使用终端注册时间:追溯用户近三年内的有效换机行为下，取T7次使用终端注册时间",
        "T8使用终端厂商:追溯用户近三年内的有效换机行为下，取T8次使用终端厂商",
        "T8使用终端串号:追溯用户近三年内的有效换机行为下，取T8次使用终端的终端串号",
        "T8使用终端五位码:追溯用户近三年内的有效换机行为下，取T8次使用终端的五位码",
        "T8使用终端型号:追溯用户近三年内的有效换机行为下，取T8次使用终端型号",
        "T8使用终端注册时间:追溯用户近三年内的有效换机行为下，取T8次使用终端注册时间",
        "T9使用终端厂商:追溯用户近三年内的有效换机行为下，取T9次使用终端厂商",
        "T9使用终端串号:追溯用户近三年内的有效换机行为下，取T9次使用终端的终端串号",
        "T9使用终端五位码:追溯用户近三年内的有效换机行为下，取T9次使用终端的五位码",
        "T9使用终端型号:追溯用户近三年内的有效换机行为下，取T9次使用终端型号",
        "T9使用终端注册时间:追溯用户近三年内的有效换机行为下，取T9次使用终端注册时间",
        "换机次数:追溯用户自入网起或有终端历史信息起有效的换机次数",
        "近三年使用终端台数:三年内历史使用终端个数",
        "至今使用终端台数:追溯用户自入网起或有终端历史使用终端个数",
        "近10个月流量:近10个月流量",
        "近10个月收入:近10个月收入",
        "近10个月主叫通话时长:近10个月主叫通话时长",
        "近11个月流量:近11个月流量",
        "近11个月收入:近11个月收入",
        "近11个月主叫通话时长:近11个月主叫通话时长",
        "近12个月流量:近12个月流量",
        "近12个月收入:近12个月收入",
        "本月天翼高清收入:本月天翼高清收入",
        "本年天翼高清收入:本年天翼高清收入",
        "本月酒店完美联盟收入:本月酒店完美联盟收入",
        "本年酒店完美联盟收入:本年酒店完美联盟收入",
        "本月IDC收入:本月IDC收入",
        "本年IDC收入:本年IDC收入",
        "本月互联网专线收入:本月互联网专线收入",
        "本年互联网专线收入:本年互联网专线收入",
        "本月商务专线收入:本月商务专线收入",
        "本年商务专线收入:本年商务专线收入",
        "本月组网专线收入:本月组网专线收入",
        "本年组网专线收入:本年组网专线收入",
        "企业活跃度:刻画企业员工使用电信产品的活跃情况，从而得到企业整体的活跃度。高-活跃度得分排名位于前30%的企业,中-活跃度得分排名位于中间40%的企业,低-活跃度得分排名位于最后30%的企业",
        "企业忠诚度:刻画企业员工使用电信产品的离网情况，从而得到企业整体的忠诚度。高-活跃度得分排名位于前30%的企业,中-活跃度得分排名位于中间40%的企业,低-活跃度得分排名位于最后30%的企业",
        "成员结构:统计当月企业使用的电信产品总个数",
        "职工人数:统计当月企业使用的电信产品总个数",
        "征信与信用评价:模型测算，根据企业客户名下通话次数、通话时长、上网时长、上网次数、企业名下产品个数、客户等级、计费输入等指标按照打分模型加权计算综合信用得分。分数区间：[0,10]",
        "中小企业:注册资金500万以下且不是集团、省份直管客户树的在网出账客户",
        "购物支付类APP使用次数（次）:使用移动dpi数据，汇总用户当月购物支付类APP使用次数（次）",
        "购物支付类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月购物支付类APP使用时长（分钟）",
        "购物支付类APP使用流量（MB）:使用移动dpi数据，汇总用户当月购物支付类APP使用流量（MB）",
        "旅行出行类APP使用次数（次）:使用移动dpi数据，汇总用户当月旅行出行类APP使用次数（次）",
        "旅行出行类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月旅行出行类APP使用时长（分钟）",
        "旅行出行类APP使用流量（MB）:使用移动dpi数据，汇总用户当月旅行出行类APP使用流量（MB）",
        "女性丽人类APP使用次数（次）:使用移动dpi数据，汇总用户当月女性丽人类APP使用次数（次）",
        "女性丽人类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月女性丽人类APP使用时长（分钟）",
        "女性丽人类APP使用流量（MB）:使用移动dpi数据，汇总用户当月女性丽人类APP使用流量（MB）",
        "生活服务类APP使用次数（次）:使用移动dpi数据，汇总用户当月生活服务类APP使用次数（次）",
        "生活服务类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月生活服务类APP使用时长（分钟）",
        "生活服务类APP使用流量（MB）:使用移动dpi数据，汇总用户当月生活服务类APP使用流量（MB）",
        "投资理财类APP使用次数（次）:使用移动dpi数据，汇总用户当月投资理财类APP使用次数（次）",
        "投资理财类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月投资理财类APP使用时长（分钟）",
        "投资理财类APP使用流量（MB）:使用移动dpi数据，汇总用户当月投资理财类APP使用流量（MB）",
        "系统管理类APP使用次数（次）:使用移动dpi数据，汇总用户当月系统管理类APP使用次数（次）",
        "系统管理类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月系统管理类APP使用时长（分钟）",
        "系统管理类APP使用流量（MB）:使用移动dpi数据，汇总用户当月系统管理类APP使用流量（MB）",
        "新闻资讯类APP使用次数（次）:使用移动dpi数据，汇总用户当月新闻资讯类APP使用次数（次）",
        "新闻资讯类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月新闻资讯类APP使用时长（分钟）",
        "新闻资讯类APP使用流量（MB）:使用移动dpi数据，汇总用户当月新闻资讯类APP使用流量（MB）",
        "休闲娱乐类APP使用次数（次）:使用移动dpi数据，汇总用户当月休闲娱乐类APP使用次数（次）",
        "休闲娱乐类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月休闲娱乐类APP使用时长（分钟）",
        "休闲娱乐类APP使用流量（MB）:使用移动dpi数据，汇总用户当月休闲娱乐类APP使用流量（MB）",
        "学习培训类APP使用次数（次）:使用移动dpi数据，汇总用户当月学习培训类APP使用次数（次）",
        "学习培训类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月学习培训类APP使用时长（分钟）",
        "潜在关注互联网卡公众号用户:识别未关注互联网卡相应公众号的用户打标。",
        "流失风险用户:识别可能会携号转网的目标用户，模型输出的是转网概率，取值范围为0 1 ，1是目标用户，0为否",
        "潜在4升5终端换机用户:非5G终端用户且终端使用18个月以上的用户",
        "终端品牌:当前终端厂商",
        "终端型号:当前终端型号",
        "手机上网流量（M）:上个月手机上网流量",
        "出账税后收入（元）:上个月出账收入",
        "自主漫游换卡目标用户:2019年1月至2020年2月产生国际漫游流量的移动在网出账用户",
        "新房装修潜在用户:通过分析固网DPI和移网DPI用户使用家装类APP的行为特征，识别具有装修房屋倾向的潜在用户",
        "环境监测潜在用户:根据用户家中是否有老人、儿童、孕妇，判断用户是否有环境监测的需求",
        "5G终端推荐价格分档:通过用户的出账信息、终端信息、DPI信息、收入信息等特征，预测5G终端价格分档",
        "5G终端推荐型号top1:通过用户的预测5G终端价格分档与用户的终端偏好特征，预测5G终端推荐型号top1",
        "5G终端推荐型号top2:通过用户的预测5G终端价格分档与用户的终端偏好等特征，预测5G终端推荐型号top2",
        "5G终端推荐型号top3:通过用户的预测5G终端价格分档与用户的终端偏好特征，预测5G终端推荐型号top3",
        "5G终端用户精准升5G套餐-目标用户:当前是5G终端且近三月月均使用流量800M以下的移动出账用户",
        "政企5G营销目标用户:1、名下有大于50个移动产品的企业客户包含的全部用户2、归属政企行客的移动出账用户（标签为一次性标签）",
        "政企4升5营销商校高值用户:行业属性为商校的政企客户名下的所有移动在网出账用户中，近三月平均出账金额为高价值档位的非5G套餐用户。",
        "电子渠道互联网卡高危用户分群:开通时间为2017年3月以后的电渠互联网卡用户，判断有不出账、低语音低流量行为，从而分群为不出账高危用户、低活跃用户、高风险网龄用户三类高危用户群。",
        "高校毕业生:通过对用户的毕业生类APP、大学生app的使用，毕业生相关、三方协议类，校园招聘类、人事类、弱相关类、学术网站类，招聘网站类的搜索词，识别用户是否高校毕业生",
        "是否主卡用户:是否是主卡",
        "集团网4升5潜在用户:筛选政企渠道客户名下50户用户以上集团网4升5非物联无语音用户",
        "云回看到期维系用户:提供已激活（即已绑定到摄像头）且有用户使用行为（通过小翼管家打开）的云回看用户（手机号码）清单，提前3个月生成此标签",
        "云回看未激活用户:提供未激活（即未绑定到摄像头）的云回看用户（手机号码）清单，以及该手机号绑定摄像头的状态：已绑定摄像头或未绑定摄像头",
        "天翼看家终端潜在用户:通过收集使用安防类设备的用户和使用摄像头/门铃/猫眼的用户，发现有：1. 使用安防类设备，但未买过摄像头/门铃/猫眼的用户。2. 使用摄像头/门铃/猫眼其中一种，未全部购买三个种类的用户。向这两类用户推荐安装摄像头/门铃/猫眼，使用天翼看家业务，可以把这类用户作为天翼看家潜客标签",
        "天翼看家固件版本老旧用户:天翼看家产品经理提供终端固件最新版本号，小翼管家绑定终端的实际版本号进行比对，输出非最新版本的绑定清单",
        "天翼看家终端与网络质差用户:根据当月掉线次数、离网时间、云存最后上传时间、云存上传成功率、网络质量、平台连接成功率、平均上行码流等综合判断终端或网络存在问题，以上个月内掉线次数超过本地市平均数的终端CTEI作为主ID",
        "家庭组网质差原因及解决方案:家庭网络连接WiFi质差用户",
        "千兆路由连接网关百兆口:网线插错接口",
        "网线规格差:网线不能满足速率要求",
        "综合详请:家庭WiFi网络详情",
        "天翼看家潜在用户:筛选在网宽带用户产品订购信息，使用智能网关未注册小翼app的标记推荐小翼app，注册小翼app未订购看家产品的标记推荐看家产品。",
        "是否天翼看家用户:已订购过天翼看家销售品的宽带用户，且使用智能网关和小翼管家app。",
        "是否小翼管家app注册用户:小翼管家注册清单中存在的宽带用户，且使用了智能网关设备。",
        "教育包潜在用户:根据天翼高清用户的手机上网行为和宽带上网行为判读是否具有教育类的潜在偏好。",
        "体育包潜在用户:根据天翼高清用户的手机上网行为和宽带上网行为判读是否具有体育类的潜在偏好",
        "视频包潜在用户:根据天翼高清用户的手机上网行为和宽带上网行为判读是否具有视频类的潜在偏好",
        "家庭云潜在用户:家庭云作为家庭宽带、IPTV等智慧家庭产品的补充产品，潜在用户应具有中国电信家庭用户特征，并且经常使用智慧家庭产品。",
        "是否高带宽低规格终端场景:路由器不能发挥带宽性能",
        "是否WiFi覆盖差场景:家中WiFi覆盖有死角",
        "是否无使用路由器场景:家中没有使用路由器",
        "Wi-Fi干扰强(场景):在带宽匹配、没有覆盖差的情况下，Wi-Fi设备同频干扰影响烈度",
        "e-link路由器个数:用户家庭已经存在e-link路由器的个数",
        "自购路由器个数(非e-link路由器):用户自购路由器（非e-link路由器）个数",
        "流量质差(场景):用户某个设备是否存在流量拥塞的情况",
        "网关及路由器下挂设备数量:网关或路由器下挂的设备(手机、pad等)数量",
        "网关运行时长参数:网关连续运行时间",
        "网关千兆口不足:网关千兆口个数不能满足路由器需求",
        "用户家庭网关MAC对应关系参数:存在质差的用户的网关MAC",
        "用户家庭网关厂商型号对应关系:存在质差用户家中网关的厂商与型号",
        "家庭网络质差营销建议:营销建议，针对不同质差情况的用户，推荐不同的套餐，目前有10种建议。",
        "网关类型:网关类型，判定网关属于什么类型，天翼网关还是e-8C网关等",
        "网关WiFi单双频:网关WiFi单双频",
        "网关LAN口最高速率:网关的LAN口是千兆还是百兆",
        "WiFi6潜客:判定方法：1、路由器性能与签约带宽比较，用户属于高带宽低规格终端用户，且签约带宽≥500M；2、用户无下挂路由器，且签约带宽≥500M；",
        "桥接改路由:桥接模式需要变更为路由模式，只有路由模式的网关才能支持可视化相关业务",
        "e8-C承载能力不足的各场景:用户家里网关为e8-C或e8-B，且承载能力不足；具体到每种e8-B/e8-C网关，在每种带宽下的不足情况。",
        "网关使用年限:网关设备使用年限；",
        "宽带提速:用户存在家庭网络整体流量带宽不足，即判定为宽带提速潜客；",
        "e8-C承载能力不足:用户家里网关为e8-C或e8-B，且承载能力不足",
        "不支持IPV6 的e8-C网关:表示用户家e8-C网关不支持IPV6",
        "可绑定小翼管家用户:筛选具备绑定条件且当月活跃且未绑定小翼管家app的网关用户对应的移动号码",
        "安全专线用户:筛选已备案客户关联客户视图后对应的出账互联网专线用户",
        "老旧网关更换:筛选网关类型为e8-C的用户，再根据用户近三月宽带使用情况、宽带速率和对应客户价值等条件，对老旧网关的场景划分。具体更换场景划分如下：1. 具有离网风险用户2. 近2个月不活跃3. 高价值用户4. 高价值且不能承载5. 高价值无承载问题6. 高价值低带宽7. 中价值用户8. 中价值且不能承载9. 中价值无承载问题10. 中价值低带宽11. 普通价值用户12. 普通价值且不能承载13. 普通价值无承载问题14. 普通价值低带宽15. 普通价值低带宽，近三月不活跃16. 普通价值低带宽，非家庭宽带",
        "移动出账数:移动出账用户数",
        "移动新增数:移动新发展用户数",
        "移动离网数:移动离网用户（201812移动出账用户在当前账期不出账的用户数）",
        "宽带出账数:一般宽带出账用户数",
        "宽带新增数:一般宽带新发展用户数",
        "宽带离网数:一般宽带离网用户（201812一般宽带出账用户在当前账期不出账的用户数）",
        "天翼高清出账数:IPTV出账用户数",
        "天翼高清新增数:IPTV新发展用户数",
        "天翼高清离网数:IPTV离网用户（201812IPTV出账用户在当前账期不出账的用户数）",
        "固话出账数:固话出账用户数",
        "固话新增数:固话新发展用户数",
        "固话离网数:固话离网用户（201815移动出账用户在当前账期不出账的用户数）",
        "酒店完美联盟出账数:截止当前月份在用酒店完美联盟销售品的出账用户",
        "酒店完美联盟新增数:截止当前月份在用酒店完美联盟销售品的新增用户",
        "酒店完美联盟离网数:截止当前月份在用酒店完美联盟销售品的离网用户",
        "互联网专线出帐用户数:互联网专线出帐用户数",
        "商务专线出帐户数:商务专线出帐户数",
        "组网专线出帐用户数:组网专线出帐用户数",
        "互联网专线新增用户数:互联网专线新增用户数",
        "商务专线新增用户数:商务专线新增用户数",
        "组网专线新增用户数:组网专线新增用户数",
        "互联网专线离网用户数:互联网专线离网用户数",
        "商务专线离网用户数:商务专线离网用户数",
        "组网专线离网用户数:组网专线离网用户数",
        "当月企业员工欠费人数:当月企业员工欠费人数",
        "当月企业员工缴费人数:当月企业员工缴费人数",
        "本月总收入:本月总收入",
        "本年总收入:本年总收入",
        "本月移动收入:本月移动收入",
        "本年移动收入:本年移动收入",
        "本月宽带收入:本月宽带收入",
        "本年宽带收入:本年宽带收入",
        "优酷视频使用时长（分钟）:使用移动dpi数据，汇总用户当月优酷视频使用时长（分钟）",
        "优酷视频使用流量（MB）:使用移动dpi数据，汇总用户当月优酷视频使用流量（MB）",
        "腾讯视频使用次数（次）:使用移动dpi数据，汇总用户当月腾讯视频使用次数（次）",
        "腾讯视频使用时长（分钟）:使用移动dpi数据，汇总用户当月腾讯视频使用时长（分钟）",
        "腾讯视频使用流量（MB）:使用移动dpi数据，汇总用户当月腾讯视频使用流量（MB）",
        "微视使用次数（次）:使用移动dpi数据，汇总用户当月微视使用次数（次）",
        "微视使用时长（分钟）:使用移动dpi数据，汇总用户当月微视使用时长（分钟）",
        "微视使用流量（MB）:使用移动dpi数据，汇总用户当月微视使用流量（MB）",
        "腾讯直播使用次数（次）:使用移动dpi数据，汇总用户当月腾讯直播使用次数（次）",
        "腾讯直播使用时长（分钟）:使用移动dpi数据，汇总用户当月腾讯直播使用时长（分钟）",
        "腾讯直播使用流量（MB）:使用移动dpi数据，汇总用户当月腾讯直播使用流量（MB）",
        "花椒直播使用次数（次）:使用移动dpi数据，汇总用户当月花椒直播使用次数（次）",
        "花椒直播使用时长（分钟）:使用移动dpi数据，汇总用户当月花椒直播使用时长（分钟）",
        "花椒直播使用流量（MB）:使用移动dpi数据，汇总用户当月花椒直播使用流量（MB）",
        "虎牙直播使用次数（次）:使用移动dpi数据，汇总用户当月虎牙直播使用次数（次）",
        "虎牙直播使用时长（分钟）:使用移动dpi数据，汇总用户当月虎牙直播使用时长（分钟）",
        "虎牙直播使用流量（MB）:使用移动dpi数据，汇总用户当月虎牙直播使用流量（MB）",
        "哔哩哔哩使用次数（次）:使用移动dpi数据，汇总用户当月哔哩哔哩使用次数（次）",
        "哔哩哔哩使用时长（分钟）:使用移动dpi数据，汇总用户当月哔哩哔哩使用时长（分钟）",
        "哔哩哔哩使用流量（MB）:使用移动dpi数据，汇总用户当月哔哩哔哩使用流量（MB）",
        "学习培训类APP使用流量（MB）:使用移动dpi数据，汇总用户当月学习培训类APP使用流量（MB）",
        "地图导航类APP使用次数（次）:使用移动dpi数据，汇总用户当月地图导航类APP使用次数（次）",
        "地图导航类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月地图导航类APP使用时长（分钟）",
        "地图导航类APP使用流量（MB）:使用移动dpi数据，汇总用户当月地图导航类APP使用流量（MB）",
        "酒店住宿类APP使用次数（次）:使用移动dpi数据，汇总用户当月酒店住宿类APP使用次数（次）",
        "酒店住宿类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月酒店住宿类APP使用时长（分钟）",
        "酒店住宿类APP使用流量（MB）:使用移动dpi数据，汇总用户当月酒店住宿类APP使用流量（MB）",
        "旅游类APP使用次数（次）:使用移动dpi数据，汇总用户当月旅游类APP使用次数（次）",
        "旅游类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月旅游类APP使用时长（分钟）",
        "旅游类APP使用流量（MB）:使用移动dpi数据，汇总用户当月旅游类APP使用流量（MB）",
        "票务查定类APP使用次数（次）:使用移动dpi数据，汇总用户当月票务查定类APP使用次数（次）",
        "票务查定类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月票务查定类APP使用时长（分钟）",
        "票务查定类APP使用流量（MB）:使用移动dpi数据，汇总用户当月票务查定类APP使用流量（MB）",
        "办公工具类APP使用次数（次）:使用移动dpi数据，汇总用户当月办公工具类APP使用次数（次）",
        "办公工具类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月办公工具类APP使用时长（分钟）",
        "办公工具类APP使用流量（MB）:使用移动dpi数据，汇总用户当月办公工具类APP使用流量（MB）",
        "保险类APP使用次数（次）:使用移动dpi数据，汇总用户当月保险类APP使用次数（次）",
        "保险类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月保险类APP使用时长（分钟）",
        "保险类APP使用流量（MB）:使用移动dpi数据，汇总用户当月保险类APP使用流量（MB）",
        "代驾类APP使用次数（次）:使用移动dpi数据，汇总用户当月代驾类APP使用次数（次）",
        "代驾类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月代驾类APP使用时长（分钟）",
        "代驾类APP使用流量（MB）:使用移动dpi数据，汇总用户当月代驾类APP使用流量（MB）",
        "房产类APP使用次数（次）:使用移动dpi数据，汇总用户当月房产类APP使用次数（次）",
        "房产类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月房产类APP使用时长（分钟）",
        "房产类APP使用流量（MB）:使用移动dpi数据，汇总用户当月房产类APP使用流量（MB）",
        "快递类APP使用次数（次）:使用移动dpi数据，汇总用户当月快递类APP使用次数（次）",
        "快递类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月快递类APP使用时长（分钟）",
        "快递类APP使用流量（MB）:使用移动dpi数据，汇总用户当月快递类APP使用流量（MB）",
        "平台类APP使用次数（次）:使用移动dpi数据，汇总用户当月平台类APP使用次数（次）",
        "平台类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月平台类APP使用时长（分钟）",
        "平台类APP使用流量（MB）:使用移动dpi数据，汇总用户当月平台类APP使用流量（MB）",
        "求职招聘类APP使用次数（次）:使用移动dpi数据，汇总用户当月求职招聘类APP使用次数（次）",
        "求职招聘类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月求职招聘类APP使用时长（分钟）",
        "求职招聘类APP使用流量（MB）:使用移动dpi数据，汇总用户当月求职招聘类APP使用流量（MB）",
        "天气类APP使用次数（次）:使用移动dpi数据，汇总用户当月天气类APP使用次数（次）",
        "天气类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月天气类APP使用时长（分钟）",
        "天气类APP使用流量（MB）:使用移动dpi数据，汇总用户当月天气类APP使用流量（MB）",
        "网络电话类APP使用次数（次）:使用移动dpi数据，汇总用户当月网络电话类APP使用次数（次）",
        "网络电话类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月网络电话类APP使用时长（分钟）",
        "网络电话类APP使用流量（MB）:使用移动dpi数据，汇总用户当月网络电话类APP使用流量（MB）",
        "违章查询类APP使用次数（次）:使用移动dpi数据，汇总用户当月违章查询类APP使用次数（次）",
        "违章查询类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月违章查询类APP使用时长（分钟）",
        "违章查询类APP使用流量（MB）:使用移动dpi数据，汇总用户当月违章查询类APP使用流量（MB）",
        "医疗保健类APP使用次数（次）:使用移动dpi数据，汇总用户当月医疗保健类APP使用次数（次）",
        "医疗保健类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月医疗保健类APP使用时长（分钟）",
        "医疗保健类APP使用流量（MB）:使用移动dpi数据，汇总用户当月医疗保健类APP使用流量（MB）",
        "运营商类APP使用次数（次）:使用移动dpi数据，汇总用户当月运营商类APP使用次数（次）",
        "运营商类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月运营商类APP使用时长（分钟）",
        "运营商类APP使用流量（MB）:使用移动dpi数据，汇总用户当月运营商类APP使用流量（MB）",
        "租车打车类APP使用次数（次）:使用移动dpi数据，汇总用户当月租车打车类APP使用次数（次）",
        "租车打车类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月租车打车类APP使用时长（分钟）",
        "租车打车类APP使用流量（MB）:使用移动dpi数据，汇总用户当月租车打车类APP使用流量（MB）",
        "单机游戏类APP使用次数（次）:使用移动dpi数据，汇总用户当月单机游戏类APP使用次数（次）",
        "单机游戏类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月单机游戏类APP使用时长（分钟）",
        "单机游戏类APP使用流量（MB）:使用移动dpi数据，汇总用户当月单机游戏类APP使用流量（MB）",
        "短视频类APP使用次数（次）:使用移动dpi数据，汇总用户当月短视频类APP使用次数（次）",
        "短视频类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月短视频类APP使用时长（分钟）",
        "短视频类APP使用流量（MB）:使用移动dpi数据，汇总用户当月短视频类APP使用流量（MB）",
        "婚恋交友类APP使用次数（次）:使用移动dpi数据，汇总用户当月婚恋交友类APP使用次数（次）",
        "婚恋交友类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月婚恋交友类APP使用时长（分钟）",
        "婚恋交友类APP使用流量（MB）:使用移动dpi数据，汇总用户当月婚恋交友类APP使用流量（MB）",
        "即时通讯类APP使用次数（次）:使用移动dpi数据，汇总用户当月即时通讯类APP使用次数（次）",
        "即时通讯类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月即时通讯类APP使用时长（分钟）",
        "即时通讯类APP使用流量（MB）:使用移动dpi数据，汇总用户当月即时通讯类APP使用流量（MB）",
        "美食菜谱类APP使用次数（次）:使用移动dpi数据，汇总用户当月美食菜谱类APP使用次数（次）",
        "美食菜谱类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月美食菜谱类APP使用时长（分钟）",
        "美食菜谱类APP使用流量（MB）:使用移动dpi数据，汇总用户当月美食菜谱类APP使用流量（MB）",
        "拍摄美化类APP使用次数（次）:使用移动dpi数据，汇总用户当月拍摄美化类APP使用次数（次）",
        "拍摄美化类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月拍摄美化类APP使用时长（分钟）",
        "拍摄美化类APP使用流量（MB）:使用移动dpi数据，汇总用户当月拍摄美化类APP使用流量（MB）",
        "社交通讯类APP使用次数（次）:使用移动dpi数据，汇总用户当月社交通讯类APP使用次数（次）",
        "社交通讯类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月社交通讯类APP使用时长（分钟）",
        "社交通讯类APP使用流量（MB）:使用移动dpi数据，汇总用户当月社交通讯类APP使用流量（MB）",
        "视频类APP使用次数（次）:使用移动dpi数据，汇总用户当月视频类APP使用次数（次）",
        "视频类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月视频类APP使用时长（分钟）",
        "视频类APP使用流量（MB）:使用移动dpi数据，汇总用户当月视频类APP使用流量（MB）",
        "音乐类APP使用次数（次）:使用移动dpi数据，汇总用户当月音乐类APP使用次数（次）",
        "音乐类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月音乐类APP使用时长（分钟）",
        "音乐类APP使用流量（MB）:使用移动dpi数据，汇总用户当月音乐类APP使用流量（MB）",
        "娱乐八卦类APP使用次数（次）:使用移动dpi数据，汇总用户当月娱乐八卦类APP使用次数（次）",
        "娱乐八卦类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月娱乐八卦类APP使用时长（分钟）",
        "娱乐八卦类APP使用流量（MB）:使用移动dpi数据，汇总用户当月娱乐八卦类APP使用流量（MB）",
        "阅读类APP使用次数（次）:使用移动dpi数据，汇总用户当月阅读类APP使用次数（次）",
        "阅读类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月阅读类APP使用时长（分钟）",
        "阅读类APP使用流量（MB）:使用移动dpi数据，汇总用户当月阅读类APP使用流量（MB）",
        "运动类APP使用次数（次）:使用移动dpi数据，汇总用户当月运动类APP使用次数（次）",
        "运动类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月运动类APP使用时长（分钟）",
        "运动类APP使用流量（MB）:使用移动dpi数据，汇总用户当月运动类APP使用流量（MB）",
        "在线游戏类APP使用次数（次）:使用移动dpi数据，汇总用户当月在线游戏类APP使用次数（次）",
        "在线游戏类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月在线游戏类APP使用时长（分钟）",
        "在线游戏类APP使用流量（MB）:使用移动dpi数据，汇总用户当月在线游戏类APP使用流量（MB）",
        "主题壁纸类APP使用次数（次）:使用移动dpi数据，汇总用户当月主题壁纸类APP使用次数（次）",
        "主题壁纸类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月主题壁纸类APP使用时长（分钟）",
        "主题壁纸类APP使用流量（MB）:使用移动dpi数据，汇总用户当月主题壁纸类APP使用流量（MB）",
        "体育健身类APP使用次数（次）:使用移动dpi数据，汇总用户当月体育健身类APP使用次数（次）",
        "体育健身类APP使用时长（分钟）:使用移动dpi数据，汇总用户当月体育健身类APP使用时长（分钟）",
        "体育健身类APP使用流量（MB）:使用移动dpi数据，汇总用户当月体育健身类APP使用流量（MB）",
        "手机淘宝使用次数（次）:使用移动dpi数据，汇总用户当月手机淘宝使用次数（次）",
        "手机淘宝使用时长（分钟）:使用移动dpi数据，汇总用户当月手机淘宝使用时长（分钟）",
        "手机淘宝使用流量（MB）:使用移动dpi数据，汇总用户当月手机淘宝使用流量（MB）",
        "翼支付使用次数（次）:使用移动dpi数据，汇总用户当月翼支付使用次数（次）",
        "翼支付使用时长（分钟）:使用移动dpi数据，汇总用户当月翼支付使用时长（分钟）",
        "翼支付使用流量（MB）:使用移动dpi数据，汇总用户当月翼支付使用流量（MB）",
        "支付宝使用次数（次）:使用移动dpi数据，汇总用户当月支付宝使用次数（次）",
        "支付宝使用时长（分钟）:使用移动dpi数据，汇总用户当月支付宝使用时长（分钟）",
        "支付宝使用流量（MB）:使用移动dpi数据，汇总用户当月支付宝使用流量（MB）",
        "QQ使用次数（次）:使用移动dpi数据，汇总用户当月QQ使用次数（次）",
        "QQ使用时长（分钟）:使用移动dpi数据，汇总用户当月QQ使用时长（分钟）",
        "QQ使用流量（MB）:使用移动dpi数据，汇总用户当月QQ使用流量（MB）",
        "微信使用次数（次）:使用移动dpi数据，汇总用户当月微信使用次数（次）",
        "微信使用时长（分钟）:使用移动dpi数据，汇总用户当月微信使用时长（分钟）",
        "微信使用流量（MB）:使用移动dpi数据，汇总用户当月微信使用流量（MB）",
        "易信使用次数（次）:使用移动dpi数据，汇总用户当月易信使用次数（次）",
        "易信使用时长（分钟）:使用移动dpi数据，汇总用户当月易信使用时长（分钟）",
        "易信使用流量（MB）:使用移动dpi数据，汇总用户当月易信使用流量（MB）",
        "王者荣耀使用次数（次）:使用移动dpi数据，汇总用户当月王者荣耀使用次数（次）",
        "王者荣耀使用时长（分钟）:使用移动dpi数据，汇总用户当月王者荣耀使用时长（分钟）",
        "王者荣耀使用流量（MB）:使用移动dpi数据，汇总用户当月王者荣耀使用流量（MB）",
        "和平精英使用次数（次）:使用移动dpi数据，汇总用户当月和平精英使用次数（次）",
        "和平精英使用时长（分钟）:使用移动dpi数据，汇总用户当月和平精英使用时长（分钟）",
        "和平精英使用流量（MB）:使用移动dpi数据，汇总用户当月和平精英使用流量（MB）",
        "qq飞车使用次数（次）:使用移动dpi数据，汇总用户当月qq飞车使用次数（次）",
        "qq飞车使用时长（分钟）:使用移动dpi数据，汇总用户当月qq飞车使用时长（分钟）",
        "qq飞车使用流量（MB）:使用移动dpi数据，汇总用户当月qq飞车使用流量（MB）",
        "穿越火线-手游版使用次数（次）:使用移动dpi数据，汇总用户当月穿越火线-手游版使用次数（次）",
        "穿越火线-手游版使用时长（分钟）:使用移动dpi数据，汇总用户当月穿越火线-手游版使用时长（分钟）",
        "穿越火线-手游版使用流量（MB）:使用移动dpi数据，汇总用户当月穿越火线-手游版使用流量（MB）",
        "跑跑卡丁车使用次数（次）:使用移动dpi数据，汇总用户当月跑跑卡丁车使用次数（次）",
        "跑跑卡丁车使用时长（分钟）:使用移动dpi数据，汇总用户当月跑跑卡丁车使用时长（分钟）",
        "跑跑卡丁车使用流量（MB）:使用移动dpi数据，汇总用户当月跑跑卡丁车使用流量（MB）",
        "节奏大师使用次数（次）:使用移动dpi数据，汇总用户当月节奏大师使用次数（次）",
        "节奏大师使用时长（分钟）:使用移动dpi数据，汇总用户当月节奏大师使用时长（分钟）",
        "节奏大师使用流量（MB）:使用移动dpi数据，汇总用户当月节奏大师使用流量（MB）",
        "抖音使用次数（次）:使用移动dpi数据，汇总用户当月抖音使用次数（次）",
        "抖音使用时长（分钟）:使用移动dpi数据，汇总用户当月抖音使用时长（分钟）",
        "抖音使用流量（MB）:使用移动dpi数据，汇总用户当月抖音使用流量（MB）",
        "快手使用次数（次）:使用移动dpi数据，汇总用户当月快手使用次数（次）",
        "快手使用时长（分钟）:使用移动dpi数据，汇总用户当月快手使用时长（分钟）",
        "快手使用流量（MB）:使用移动dpi数据，汇总用户当月快手使用流量（MB）",
        "西瓜视频使用次数（次）:使用移动dpi数据，汇总用户当月西瓜视频使用次数（次）",
        "西瓜视频使用时长（分钟）:使用移动dpi数据，汇总用户当月西瓜视频使用时长（分钟）",
        "西瓜视频使用流量（MB）:使用移动dpi数据，汇总用户当月西瓜视频使用流量（MB）",
        "火山小视频使用次数（次）:使用移动dpi数据，汇总用户当月火山小视频使用次数（次）",
        "火山小视频使用时长（分钟）:使用移动dpi数据，汇总用户当月火山小视频使用时长（分钟）",
        "火山小视频使用流量（MB）:使用移动dpi数据，汇总用户当月火山小视频使用流量（MB）",
        "爱奇艺视频使用次数（次）:使用移动dpi数据，汇总用户当月爱奇艺视频使用次数（次）",
        "爱奇艺视频使用时长（分钟）:使用移动dpi数据，汇总用户当月爱奇艺视频使用时长（分钟）",
        "爱奇艺视频使用流量（MB）:使用移动dpi数据，汇总用户当月爱奇艺视频使用流量（MB）",
        "优酷视频使用次数（次）:使用移动dpi数据，汇总用户当月优酷视频使用次数（次）",
        "天翼高清教育内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工教育偏好用户标签1、结合教育热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合教育内容偏好标签策划内容专题3、结合教育内容偏好推荐关联产品",
        "天翼高清增值业务订购行为:结合天翼高清用户订购记录，针对近1年内新订/续订有3次或以上同类产品进行加工形成增值业务订购偏好",
        "智能机顶盒潜在用户:有ITV业务账号、机顶盒为非智能机顶盒",
        "ITV内容精准营销模板:1、针对20-50岁的女性、未订购用户、偏好影视内容的用户，配置影视模板2、针对5-13岁/25-45岁、偏好少儿内容的用户，配置少儿模板",
        "高带宽低规格场景（itv专用）:用户存在网络质差，可以通过全屋WiFi套餐升级。",
        "带宽升速（itv专用）:流量使用占比高，带宽不足的情况",
        "客户名下外省手机号卡数（日）:统计当前客户对应身份证号码在外省办理的移动在网产品个数。",
        "客户名下外省宽带数（日）:统计当前客户对应身份证号码在外省办理的宽带在网产品个数。",
        "互联网卡4升5目标用户:互联网卡4升5下省目标用户分为接触和非接触两类",
        "是否当月累计SA登网:使用4G、5G用户登网数据，打标当月累计SA登网用户。",
        "是否当月累计NSA登网:使用4G、5G用户登网数据，打标当月累计NSA登网用户。",
        "是否当月累计5G登网用户:使用4G、5G用户登网数据，当月SA登网和NSA登网用户排重，打标当月累计5G登网用户。",
        "影视宽带（智家小果）:针对有第二屏（2个电视）、IPTV不活跃、影视内容喜爱者（爱奇艺/非爱奇艺），营销智家小果产品。",
        "是否橙分期用户:判断用户是否是橙分期用户",
        "橙分期到期时间:橙分期生效时间+橙分期期限",
        "家庭构成-四口之家:识别用户家庭的构成情况",
        "家庭构成-五口之家:识别用户家庭的构成情况",
        "家庭构成-六口之家:识别用户家庭的构成情况",
        "千兆全屋Wi-Fi潜客:表示用户签约带宽已≥1000M，但未订购全屋WiFi的新用户，或签约带宽已≥1000M，但需要进行套餐升级的全屋WiFi存量用户",
        "端网匹配:针对签约带宽≥1000M，但网关最高支持速率无法达到千兆（900M），或网关上行接入方式不是10GPON网关的用户，更换10GPON网关",
        "B站大会员潜在用户:有B站付费页面访问记录的用户",
        "B站偏好用户:根据访问B站频次、流量的情况，筛选出B站忠实用户，该标签不包含B站付费大会员潜在用户（付费大会员意向用户请应用【B站大会员潜在用户】标签）",
        "非B站视频偏好用户:根据其他视频应用（B站外）的访问频次及流量，构建模型，识别偏好用户",
        "流量骤减时刻:手机号流量小时级排序，与上一小时的差值排序第一的时刻",
        "流量激增时刻:手机号流量小时级排序，与上一小时的差值排序最后的时刻",
        "活动时段:流量大于5的时刻，凌晨4点至23点",
        "休息睡眠时段:通过用户驻留时长，统计用户活动时段以外，无短信、流量和通话等行为的时间",
        "忙时:活动时段中流量小于平均流量的时刻",
        "闲时:活动时段中流量大于等于平均流量的时刻",
        "5G升级流量包(9.9元号码级版)目标用户:筛选在网超过6个月时长，非互联网卡或日租卡套餐的非融合移动用户中满足以下任一条件的用户：（1）5G手机非5G套餐用户（办理5G套餐或5G升级包）；（2）近6月月均税后出账收入>=60元；（3）流量活跃未溢出用户(指连续6月)且近6月月均税后出账收入[30,60)元；支撑5G流量升级包（9.9元号码升级版）营销活动，使用时长一年，标签数据按月增补更新。",
        "用户签约带宽信息参数:用户的签约带宽信息",
        "新版全屋WiFi潜客:针对存在质差问题的宽带用户，推荐全屋WiFi套餐；针对已经是全屋WiFi套餐的用户还存在质差问题的，推荐全屋WiFi升级",
        "终端卡槽类型:终端卡槽内运营类型打标",
        "是否上网主用卡:通过数据自注册数据中imsi信息判断用户卡槽归属运营商情况口径1： 对“电信+电信”终端的两个电信号码的标签标记为1，均视为上网主用卡。口径2：对“电信+空”、“单电信卡”的电信号码的标签标记为1，视为上网主用卡。口径3： 根据每日流量补充未识别用户，若日流量大于阈值，标记为3，视为上网主用卡，流量小于阈值标记为2，视为上网备用卡。口径4：流量阈值暂采用1%分位点，后续视情况优化。",
        "5G终端用户版本信息:判断用户当前手机终端是否支持SA，是否有单独SA开关，以及开关是否默认打开状态。",
        "是否老旧套餐:2017年以前上市，非畅享、非5G，流量单价高的老旧套餐用户，开展套餐升级（静态标签，不更新）",
        "是否当日SA登网:使用4G、5G用户登网数据，打标当日SA登网用户。",
        "是否当日NSA登网:使用4G、5G用户登网数据，打标当日NSA登网用户。",
        "是否当日5G登网:使用4G、5G用户登网数据，当日SA登网和NSA登网用户排重，打标当日5G登网用户。",
        "游戏宽带:识别用户使用在线游戏APP，可以快速找到潜在用户，助力游戏宽带快速出量。",
        "新版天翼看家潜客:通过判断用户家里是否有老人或者孩子，如果有老人小孩且没有摄像头安装的，作为看家潜客，主要推荐摄像头；如果没有看家设备，也没有老人小孩，则推荐门铃。",
        "5G开关打开用户:SA登网用户或手机5G开关打开的用户 均判定为“5G开关打开用户”。",
        "5G高值免办用户:筛选移动在网5G终端用户，限制流量>=5G且月收入>=99元划定为高价值免办用户。",
        "宽带下挂携号转网潜客:中国电信宽带下挂的异网手机号，可以进行异网策反",
        "星卡定向流量潜客:通过采集用户通过宽带访问APP（网站/APP/软件）等的频度和内容，结合星卡套装的规则，将中高频次访问APP的用户定义为星卡目标客户",
        "潜在单C转融用户:预测潜在的单C转融用户。根据用户特征信息建模并预测是否为潜在单C转融用户。",
        "政企4升5-202106:条件1：政企客户视图中，企业名称在政企存量清单高价值客户范围中（存量清单014范围）。条件2：政企客户视图中，客户名下移动用户在200线以上。满足上述任意1组条件，且截止6月底仍为4G用户的，即纳入本次派单范围。",
        "房产类app使用次数:使用移动dpi数据，汇总用户当月家居装修、租房买房类app的使用次数。",
        "房产类app使用时长:使用移动dpi数据，汇总用户当月家居装修、租房买房类app的使用时长。单位：分钟",
        "房产类app使用天数:使用移动dpi数据，汇总用户当月家居装修、租房买房类app的使用天数。",
        "房产类app使用个数:使用移动dpi数据，汇总用户当月家居装修、租房买房类app的使用个数。",
        "家居装修类APP当月访问次数:使用移动dpi数据，汇总用户当月家居装修类app的使用次数。",
        "家居装修类APP当月使用流量:使用移动dpi数据，汇总用户当月家居装修类app的使用流量。单位：MB",
        "家居装修类APP当月访问天数:使用移动dpi数据，汇总用户当月家居装修类app的使用天数。",
        "家居装修类APP当月访问个数:使用移动dpi数据，汇总用户当月家居装修类app的使用个数。",
        "租房买房类APP当月访问次数:使用移动dpi数据，汇总用户当月租房买房类app的使用次数。",
        "租房买房类APP当月使用流量:使用移动dpi数据，汇总用户当月租房买房类app的使用流量。单位：MB",
        "租房买房类APP当月访问天数:使用移动dpi数据，汇总用户当月租房买房类app的使用天数。",
        "租房买房类APP当月访问个数:使用移动dpi数据，汇总用户当月租房买房类app的使用天数。",
        "货拉拉APP当月访问次数:使用移动dpi数据，汇总用户当月货拉拉app的使用次数。",
        "货拉拉APP当月使用流量:使用移动dpi数据，汇总用户当月货拉拉app的使用流量。单位：MB",
        "货拉拉APP当月访问天数:使用移动dpi数据，汇总用户当月货拉拉app的使用天数。",
        "天翼高清用户基础画像:围绕用户入网时间、活跃情况、收视行为、订购记录、订购ARPU、积分信息等维度数据，形成多类用户分群，并针对不同用户群体设计不同的活动形式、推荐内容及推送渠道",
        "天翼高清电视剧内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工电视剧偏好用户标签1、结合电视剧热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合电视剧内容偏好标签策划内容专题3、结合电视剧内容偏好推荐关联产品",
        "天翼高清电影内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工电影偏好用户标签1、结合电影热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合电影内容偏好标签策划内容专题3、结合电影内容偏好推荐关联产品",
        "天翼高清少儿内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工少儿偏好用户标签1、结合少儿热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合少儿内容偏好标签策划内容专题3、结合少儿内容偏好推荐关联产品",
        "天翼高清综艺内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工综艺偏好用户标签1、结合综艺热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合综艺内容偏好标签策划内容专题3、结合综艺内容偏好推荐关联产品",
        "天翼高清动漫内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工动漫偏好用户标签1、结合动漫热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合动漫内容偏好标签策划内容专题3、结合动漫内容偏好推荐关联产品",
        "天翼高清纪录片内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工纪录片偏好用户标签1、结合纪录片热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合纪录片内容偏好标签策划内容专题3、结合纪录片内容偏好推荐关联产品",
        "天翼高清音乐内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工音乐偏好用户标签1、结合音乐热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合音乐内容偏好标签策划内容专题3、结合音乐内容偏好推荐关联产品",
        "天翼高清生活内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工生活偏好用户标签1、结合生活热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合生活内容偏好标签策划内容专题3、结合生活内容偏好推荐关联产品",
        "天翼高清游戏内容偏好:根据天翼高清用户收视行为以及统一媒资内容标签，加工游戏偏好用户标签1、结合游戏热门内容榜单推荐热门内容（智家公司定期发布各业务类型热门内容榜单）2、结合游戏内容偏好标签策划内容专题3、结合游戏内容偏好推荐关联产品",
        "景区宣传场景潜客:筛选一级行业为居民服务业，二级行业为住宿业、旅游业，三级行业为旅游饭店、旅行社、旅游景区、旅游文化的政企客户，再筛选政企客户名称中含有‘旅游、旅行、酒店、景点、景区、动物园、游乐园、公园’字样、且统一社会信用代码为91/92开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "通用业务宣传场景潜客:筛选一级行业为住建行业，且二级行业为建筑业、装修业、物业管理，客户名称带有'装修、装饰、家装、物业、物管'字样；或一级行业综合服务业，且二级行业为商业地产，客户名称带有'房地产、地产'字样；或一级行业交通物流行业，且二级行业为交通运输、物流业，客户名称带有'快递、速递、物流、速运'字样；或一级行业金融行业客户，且二级行业为银行业、证券业、保险业，客户名称带有'银行、证券、保险'字样；且统一社会信用代码为91/92开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "商彩体验临期客户:将商务彩铃到达客户根据客户体验到期时间进行分档：1、已到期：体验到期时间<=当前账期；2、30个自然日内：当前账期>体验到期时间>=当前账期+30天；3、60个自然日内：当前账期+30天>体验到期时间>=当前账期+60天；4、90个自然日内：当前账期+60天>体验到期时间>=当前账期+90天；4、90个自然日以上：体验到期时间>当前账期+90天；",
        "商彩到期续约潜客:根据商务彩铃到达客户的到期时间，筛选临期续约需求客户，并根据到期时间进行分档：1、已到期：客户到期时间<=当前账期；2、30个自然日内：当前账期>客户到期时间>=当前账期+30天；3、60个自然日内：当前账期+30天>客户到期时间>=当前账期+60天；4、90个自然日内：当前账期+60天>客户到期时间>=当前账期+90天；4、90个自然日以上：客户到期时间>当前账期+90天。* 客户到期日期=客户创建日期+365个自然日",
        "音频彩铃历史订购客户升商彩潜客:在过去3年有音频彩铃订购记录且仍在网的客户中剔除商务视频彩铃客户到达客户，即为音频彩铃历史订购客户升商彩潜客",
        "音频彩铃在网客户升商彩潜客:在有过音频彩铃订购记录且仍在网的客户中剔除商务视频彩铃客户到达客户，即为音频彩铃在网客户升商彩潜客",
        "已订来电名片未订商彩潜客:订购过来电名片且在网客户中剔除商务视频彩铃客户到达客户，即为已订来电名片未订商彩潜客",
        "已订挂机名片未订商彩潜客:订购过挂机名片且在网客户中剔除商务视频彩铃客户到达客户，即为已订挂机名片未订商彩潜客",
        "已订AI通信助理未订商彩潜客:订购过AI通信助理且在网客户中剔除商务视频彩铃客户到达客户，即为已订AI通信助理未订商彩潜客",
        "当日卫星通话活跃:当天卫星通话时长>0",
        "当日卫星通话高活跃:当天卫星通话次数>1",
        "当日卫星通话次数:当天卫星通话次数",
        "当日卫星通话时长:当天号码的卫星通话总时长，单位（分钟）",
        "当日是否发送卫星短信:当天是否发过卫星短信",
        "当日卫星短信次数:当天发送卫星短信的次数",
        "最佳营销时刻:活动时段中10点至17点间流量总和为最大流量app两倍的时刻或者app标签为短视频、社会资讯、微博的时刻",
        "是否流量抑制用户:当前用户，当月每天所使用流量与套内流量组合，根据模型参数饱和度临界值，依次累加用户每天使用流量总和，若在当月使用流量达到饱和度临界值，则该用户为流量抑制用户",
        "流量抑制临界天:当前用户，当月每天所使用流量与套内流量组合，根据模型参数饱和度临界值，依次累加用户每天使用流量总和，若在当月使用流量达到饱和度临界值，，则该用户为流量抑制用户，判断用户到达临界值的日期，达到流量饱和度的天数即为抑制流量天",
        "流量抑制临界流量:截至用户流量抑制临界值当天，统计月初至当天的流量总和",
        "流量抑制临界饱和度:划定流量抑制的阈值，默认为60%（模型参数）",
        "流量抑制系数:模型输出系数，反应用户的抑制行为的强烈程度。",
        "工作地TOP1常驻基站小区ID:通过数据汇总打标用户工作地最常出现的top1基站小区",
        "工作地TOP2常驻基站小区ID:通过数据汇总打标用户工作地最常出现的top2基站小区",
        "居住地TOP1常驻基站小区ID:通过数据汇总打标用户居住地最常出现的top1基站小区",
        "居住地TOP2常驻基站小区ID:通过数据汇总打标用户居住地最常出现的top2基站小区",
        "工作地TOP1常驻基站小区类型:使用数据汇总打标用户工作地最常出现的top1基站小区，通过基站信息数据识别是4G还是5G基站",
        "工作地TOP2常驻基站小区类型:使用数据汇总打标用户工作地最常出现的top2基站小区，通过基站信息数据识别是4G还是5G基站",
        "居住地TOP1常驻基站小区类型:使用数据汇总打标用户居住地最常出现的top1基站小区，通过基站信息数据识别是4G还是5G基站",
        "居住地TOP2常驻基站小区类型:使用数据汇总打标用居住作地最常出现的top2基站小区，通过基站信息数据识别是4G还是5G基站",
        "工作地TOP1常驻基站小区覆盖类型:使用数据汇总打标用户工作地最常出现的top1基站小区，通过基站信息数据识别基站覆盖类型是室内、室外、室内兼室外",
        "工作地TOP2常驻基站小区覆盖类型:使用数据汇总打标用户工作地最常出现的top2基站小区，通过基站信息数据识别基站覆盖类型是室内、室外、室内兼室外",
        "居住地TOP1常驻基站小区覆盖类型:使用数据汇总打标用户居住地最常出现的top1基站小区，通过基站信息数据识别基站覆盖类型是室内、室外、室内兼室外",
        "居住地TOP2常驻基站小区覆盖类型:使用数据汇总打标用户居住地最常出现的top2基站小区，通过基站信息数据识别基站覆盖类型是室内、室外、室内兼室外",
        "工作地TOP1常驻基站小区忙闲情况:使用数据汇总打标用户工作地最常出现的top1基站小区，通过基站信息数据识别基站下行BPR使用率，取值范围0-100%之间。",
        "工作地TOP2常驻基站小区忙闲情况:使用数据汇总打标用户工作地最常出现的top2基站小区，通过基站信息数据识别基站下行BPR使用率，取值范围0-100%之间。",
        "居住地TOP1常驻基站小区忙闲情况:使用数据汇总打标用户居住地最常出现的top1基站小区，通过基站信息数据识别基站下行BPR使用率，取值范围0-100%之间。",
        "居住地TOP2常驻基站小区忙闲情况:使用数据汇总打标用户工作地最常出现的top2基站小区，通过基站信息数据识别基站下行BPR使用率，取值范围0-100%之间。",
        "工作地TOP1常驻基站小区是否5G覆盖:使用数据汇总打标用户工作地最常出现的top1基站小区，通过基站信息数据识别距离常驻基站小区附近是否有5G小区覆盖。",
        "工作地TOP2常驻基站小区是否5G覆盖:使用数据汇总打标用户工作地最常出现的top2基站小区，通过基站信息数据识别距离常驻基站小区附近是否有5G小区覆盖。",
        "居住地TOP1常驻基站小区是否5G覆盖:使用数据汇总打标用户居住地最常出现的top1基站小区，通过基站信息数据识别距离常驻基站小区附近是否有5G小区覆盖。",
        "居住地TOP2常驻基站小区是否5G覆盖:使用数据汇总打标用户工作地最常出现的top2基站小区，通过基站信息数据识别距离常驻基站小区附近是否有5G小区覆盖。",
        "B站付费会员潜在用户(高概率）:根据用户的终端类型、套餐价值、流量包订购情况以及针对视频类app使用流量、次数、天数等行为建立模型，识别B站会员潜在付费用户",
        "产权客户证件下移动用户数:统计同一产权客户证件下的移动号卡数量",
        "使用客户证件下移动用户数:统计同一使用客户证件下的移动号卡数量",
        "套流匹配度:在网老套餐用户的在用(主套餐+流量包)的总流量，与当前同价位主流套餐的流量是否匹配",
        "流量饱和度:用户实际流量使用情况与实际订购的所有流量（主销售品+当月订购流量包）占比，根据最终情况将饱和度分为四盒档位：10%以下、10%~80%、80%~100%、100%以上",
        "套餐档位-省份口径:以省份上传销售品信息为基准，最终套餐档位=套餐档位 - 优惠金额 + 其他优惠增减，将用户套餐分档为：0~19，19~59，59~99，99~199，199以下",
        "套餐档位-集约口径:以集团集约销售品信息为基准，最终套餐档位=套餐档位 - 优惠金额 + 其他优惠增减，将用户套餐分档为：0~19，19~59，59~99，99~199，199以下",
        "是否本月移动新发展用户:限制产品类型为移动，根据用户开通时间，判断用户是否本月新增",
        "是否本年移动新发展用户:限制产品类型为移动，根据用户开通时间，判断用户是否本年新增",
        "全屋WiFi到期续约标签:表示全屋WiFi套餐合约已经到期（≥12个月/24个月）的用户，或者临期1、2、3个月到期的用户",
        "FTTR潜客标签:结合elink规格和覆盖情况，输出全屋WiFi存量用户临期1/2/3个月和到期未续约用户，针对不同时段临期/到期用户采取分段式营销策略",
        "新羽公众高价值用户:限制当月出账的主卡用户，且终端类型为2/3G和4G非VOLTE；有语音+流量行为，且使用流量大于等于1G；套餐价值档位大于等于79元的高价值用户",
        "是否小合约用户:根据订购的小合约销售品信息，判定用户是否是小合约用户，标签值：是或否。",
        "小合约类别:根据小合约归属类别，取小合约对应的类别：1，5G小合约；2，千兆小合约；3，加号卡小合约；4，加宽带小合约；5，WiFi小合约；6，看家小合约；7，全屋智能小合约；8，移动终端小合约；9，固网终端小合约；10，融云小合约；11，融AI小合约；12，融安全小合约；13，自有应用小合约；14，生态权益小合约；15，其他；",
        "小合约价值量:根据订购的小合约产品信息，取当前有效的小合约产品的累计价值，单位：元。",
        "是否携入用户:识别用户是否为异网携入用户，标签值：是或否。",
        "携入来源:识别异网携入用户的具体来源，标签值：移动、联通。",
        "天翼云盘使用流量:天翼云盘APP当月累计使用移动流量",
        "骑行偏好:根据用户当月APP使用情况，判断用户是否为骑行类偏好用户",
        "用户使用APP个数:用于识别移动用户上月访问APP总数，标签值：如0,1,2等",
        "短视频偏好:根据用户当月APP使用情况，判断用户是否为短视频类app偏好用户",
        "云盘使用偏好:根据用户当月APP使用情况，判断用户是否为云盘类app偏好用户",
        "是否有套外流量收入:识别用户当月是否有套外溢出流量收入，即剔除套内流量、可选包的流量收入，单位元",
        "是否到达换机周期:根据用户历史终端使用周期，预测用户的平均换机周期，本将用户平均换机周期与当前终端使用时间进行对比（总持有时长/历史终端个数）注：当用户只有一款手机，换机平均周期=该用户同款机型用户平均换机时长的均值1、已超期服役N个月 （终端首次注册月份数-平均换机周期>3）2、已达换机周期（终端首次注册月份数-平均换机周期 在0-3之间）3、距离换机周期还差N个月（终端首次注册月份数-平均换机周期<0）",
        "高值非千全屋WiFi潜客:拍照2023年3月账期数据，筛选全屋wifi潜客用户群，限制宽带速率>1000M，并结合客户价值，输出标签值：1、129-169非千全屋wifi潜客2、169以上非千全屋wifi潜客",
        "iTV本月沉默天数:用于识别iTV用户最近连续沉默天数，iTV连续沉默N日，如当前为T日，即T-1到T-N日沉默，前T-N-1日不沉默",
        "iTV终端型号:用于识别用户iTV终端型号，根据iTV串号宽表加工，识别用户iTV终端型号，如E909、E8205等---机顶盒硬件型号",
        "iTV产品型号:iTV产品的具体型号，如新高清（中兴）、新高清（华为）等，通过iTV维表关联取val_name---机顶盒厂商",
        "iTV终端制式:用户当前使用的iTV机顶盒制式，包含标清、高清、智能高清等",
        "是否新羽23G终端拍照用户:当月终端类型为2、3G的出账用户，当月无5G流量，未产生volte信令，非连续三个月三零",
        "是否新羽4G非volte终端拍照用户:当月终端类型为4G非volte终端的出账用户，当月无5G流量，未产生volte信令，非连续三个月三零",
        "是否需版本升级后支持VOLTE功能用户:当月终端类型为终端公司提供的6款需版本升级后支持VOLTE功能的终端型号并且系统版本号不在终端公司提供的版本号里的出账用户，当月无5G流量，未产生volte信令，非连续三个月三零",
        "是否版本升级实现VOLTE默开用户:当月终端类型为终端公司提供的6款需版本升级后支持VOLTE功能的终端型号并且系统版本号不在终端公司提供的版本号里的出账用户，当月无5G流量，未产生volte信令，非连续三个月三零",
        "是否终端支持VOLTE但开关未打开用户:当月终端类型为4G支持volte终端的出账用户，当月无5G流量，未产生volte信令，非连续三个月三零，自注册记录中关联到volte开关未打开",
        "是否未知终端用户:当月终端类型无法识别的出账用户，当月无5G流量，未产生volte信令，非连续三个月三零",
        "5G存量融合未满卡:限制证件类型为个人，用户套餐是否 5G=是，客户融单属性=211或浅融合，客户名下号卡张数=2张、1张，且不等于0，套餐价值档位≥39元",
        "4G存量融合未满卡:限制证件类型为个人，用户套餐是否 5G=否，客户融单属性=211或浅融合，客户名下号卡张数=2张、1张，且不等于0，套餐价值档位≥39元",
        "单C客户转融:限制证件类型为个人，客户融单属性=单移，套餐价值档位≥39元",
        "单宽客户转融:限制证件类型为个人，客户融单属性=单宽，套餐价值档位≥39元",
        "普法宣传场景潜客:筛选一级行业为政法公安，二级行业为政法公安，三级行业为政法的政企客户，再筛选政企客户名称中含有‘法院、检察院’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "廉政宣传场景潜客:筛选客户名称中含有‘委员会、纪委、反贪、反腐败、纪检’字样的客户 ，再剔除商务彩铃到达客户，则为该行业潜客",
        "防诈骗宣传场景潜客:筛选一级行业为政法公安，二级行业为政法公安，三级行业为公安的政企客户，再筛选政企客户名称中含有‘公安、派出所、反诈中心、防诈骗中心、反诈骗中心’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "交通安全宣传场景潜客:筛选一级行业为政法公安，二级行业为政法公安，三级行业为公安的政企客户，再筛选政企客户名称中含有‘公安、派出所、交警’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "平安建设场景潜客:筛选一级行业为政法公安，二级行业为政法公安，三级行业为公安的政企客户，且客户名称中含有‘公安、派出所、街道办、居委、村委、居民委员会、村民委员会’字样的客户；或一级行业为政务行业，二级行业为政府机关、社会服务、市场监管、政务其他，且客户名称中含有‘公安、派出所、街道办、居委、村委、居民委员会、村民委员会’字样的客户；且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "税宣场景潜客:筛选一级行业为政务行业，二级行业为政府机关、社会服务、市场监管、政务其他，再筛选政企客户名称中含有‘税务、稽查’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "城市文旅宣传场景潜客:筛选一级行业为政务行业，二级行业为文体宣传，再筛选政企客户名称中含有‘宣传、广播电视、文旅、文化、广电’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "创文创卫宣传场景潜客:筛选一级行业为政务行业，二级行业为文体宣传，再筛选政企客户名称中含有‘宣传、广播电视、文明办、创文办、创卫办、广电’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "大型活动宣传场景潜客:筛选一级行业为政务行业，二级行业为文体宣传，再筛选政企客户名称中含有‘奥运、亚运、广交会、进博会、全运、大运’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "征兵宣传场景潜客:筛选一级行业为要客服务，再筛选政企客户名称中含有‘征兵办、国防动员、武装部’字样的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "防灾科普场景潜客:筛选一级行业为应急行业，二级行业为应急，再筛选政企客户名称中含有‘消防、应急管理、救援、减灾办、地震、气象、水利’字样、且统一社会信用代码为11/12/15/19/51开头的客户",
        "乡村振兴场景潜客:筛选一级行业为农业农村行业，再筛选政企客户名称中含有‘农业、振兴办、扶贫办、村委、乡政府’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "疾病预防科普场景潜客:筛选一级行业为卫健行业，二级行业为医疗机构，三级行业为医院、基层医疗机构、专业公卫机构的政企客户，再筛选政企客户名称中含有‘疾控中心、健康、卫生、保健、卫健、医院、诊所’字样、且统一社会信用代码为12/51/91/92开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "安全教育场景潜客:筛选政企客户名称中含有‘教育局、教育厅、教育部’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "招生宣传场景潜客:筛选一级行业为教育行业，二级行业为教育院校，三级行业为幼儿园、小学、中等院校、高等院校、培训机构的政企客户，再筛选政企客户名称中含有‘幼儿园、学校、大学、中学、学院、小学、高中、初中、研究院、研究所、技校’字样、且统一社会信用代码为11/12/15/19/51开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "餐饮宣传场景潜客:筛选一级行业为居民服务业，二级行业为住宿业、餐饮业，三级行业为旅游饭店、一般旅馆、正餐服务、快餐服务的政企客户，再筛选政企客户名称中含有‘餐饮、饮食、美食、烘焙、咖啡、茶’字样、且统一社会信用代码为91/92开头的客户，再剔除商务彩铃到达客户，则为该行业潜客",
        "网络质差:网关承载力可承载，签约带宽>lan_capacity时，网关承载力不能承载否则，网关承载力可承载；标签主数据：1:可承载；0:不能承载。",
        "是否卫星终端用户:是否卫星终端，当前卫星终端共计19类：1，是；0，否；-1，未知",
        "宽带下联智能家居识别数标签:网关下挂设备表中记录的同一账号下挂终端数量",
        "泛智能终端型号:全屋智能泛智能终端设型号，数据源自于数字生活公司",
        "泛智能终端类型:泛智能终端分类：由数字生活公司家居平台定义，取值为：001 智能音箱 002 语音遥控器 003 智能机顶盒 004 智能插座 005 智能遥控 006 环境检测 007 物联网关 008 安防传感器 009 智能灯具 010 智能开关 011 智能面板 012 智能按钮 013 智能窗帘 014 智能门锁 015 智能家电 016 智能机器人 017 健康个护 018 智能鞋柜 019 VR眼镜 020 智能电话机 021 智能投屏器 022 智能马桶盖 023 其他家居 024 智能摄像头 025 智能组网 026 智能猫眼 027 智能投影仪",
        "换卡优先级:1、最高优先级：2022年7月至今曾出境次数大于等于2次的沃达丰卡用户；2、高优先级：2022年7月至今曾出境1次的沃达丰卡用户（不含曾出境至未开通自主漫游方向用户）；3、中优先级：1省公司活跃、主动开通国漫权限、未出境的沃达丰卡用户；4、低优先级：6省公司（北京、内蒙、山东、云南、浙江、重庆）被动开通权限用户，和31省公司三无用户的并集，剔除曾出境（支持自主漫游方向）用户；5、暂不换卡：2022年7月至今曾出境至17个目前不支持自主漫游方向的用户（只要其中1个方向不支持自主漫游，则为暂不换卡用户。）；-1、未知：不符合以上情况的未知用户",
        "近3个月是否三无(含境内外):识别用户近3个月，是否境内、境外话单均三无。三无指的是：无语音、无流量、无短信行为的用户",
        "是否近3月开通国漫权限:识别用户近3个月，是否开通国漫权限",
        "是否2022年1月至今开通国漫权限:识别用户2022年1月至今，是否开通国漫权限",
        "是否2022年7月至今曾出境(不含未开通自主漫游方向):通过是否有境外话单行为，识别用户2022年7月至今是否出境（不含未开通自主漫游方向）",
        "是否2022年7月至今曾出境大于等于2次(不含未开通自主漫游方向):结合境内和境外话单行为，识别用户2022年7月至今是否出境两次及以上（不含未开通自主漫游方向）",
        "上月至今是否无境外话单有境内话单:结合境内和境外话单行为，识别用户近两月是否有境内话单，无境外话单",
        "卡激活与国漫权限开通同天:该标签只针对6省公司（北京、内蒙、山东、云南、浙江、重庆）提供",
        "开通国漫权限时间:用户开通国漫权限的时间",
        "是否2022年7月至今曾出境大于等于1次(不含未开通自主漫游方向):20220701账期之后任意一个月有过境外话单记录的用户",
        "是否去过17国或地区方向:通过境外话单判断，是否去过17个划定的国家或地区",
        "是否连续三个月都处于停机状态:用户状态是否连续三个月都是停机",
        "是否连续两个月都只有境外话单而没有境内话单:是否连续两个月都只有境外话单而没有境内话单",
        "当日是否卫星套外资费:当天打卫星电话或发卫星短信是否产生了套外费用，计费总费用>0",
        "是否已有卫星终端未办业务潜客:当前终端是卫星终端，但未办理卫星业务的全国移动在网用户。只针对13个省份剔除本省数据后下发：西藏，新疆，四川，江苏，浙江，湖北，青海，内蒙，云南，甘肃，重庆，贵州，海南。",
        "当日新增卫星有端无业用户:仅打标统计卫星终端的首次注册时间为当日，且未订购卫星业务的用户（卫星业务包括：'7120110001000022','7120110001000023','7120110001000024','7120110001000025','7120110001000031','7120110001000032','7120110001000033'）",
        "当日首次卫星电话通话事件:是否当日第一次卫星通话：限制用户当前手机终端是卫星手机终端(当日末次自注册信息为直连终端)、已订购卫星业务，且当日首次拨打卫星电话（卫星业务包括：'7120110001000022','7120110001000023','7120110001000024','7120110001000025','7120110001000031','7120110001000032','7120110001000033'）",
        "是否卫星有端有业无连星用户:限制用户当前手机终端是卫星手机终端(当月末次自注册信息为直连终端)、已订购卫星业务，且当月的每天都无连星操作（卫星业务包括：'7120110001000022','7120110001000023','7120110001000024','7120110001000025','7120110001000031','7120110001000032','7120110001000033'）",
        "是否卫星有端有业有连星无通话用户:限制用户当前手机终端是卫星手机终端(当月末次自注册信息为直连终端)、已订购卫星业务，且当月有过连星操作，但一整个月都无通话的用户（卫星业务包括：'7120110001000022','7120110001000023','7120110001000024','7120110001000025','7120110001000031','7120110001000032','7120110001000033'）",
        "是否卫星有端有业有通话用户:限制用户当前手机终端是卫星手机终端(当月末次自注册信息为直连终端)、已订购卫星业务，且卫星当月有过通话时长>0（卫星业务包括：'7120110001000022','7120110001000023','7120110001000024','7120110001000025','7120110001000031','7120110001000032','7120110001000033'）",
        "卫星通话时长到达10分钟:限制用户当前手机终端是卫星手机终端(当月末次自注册信息为直连终端)、已订购卫星功能包，且当月有过单次卫星通话时长≥10分钟的行为（卫星功能包：'7120110001000022'）",
        "卫星套内体验时长溢出:限制用户当前手机终端是卫星手机终端(当月末次自注册信息为直连终端)、已订购卫星业务，且当月产生了套外费用（卫星业务包括：'7120110001000022','7120110001000023','7120110001000024','7120110001000025','7120110001000031','7120110001000032','7120110001000033'）",
        "是否有端无业用户:限制用户当前终端是卫星终端，但未办理卫星业务的移动在网用户",
        "是否办理卫星产品用户:识别用户是否已办理卫星业务或功能包（已订购卫星业务、功能包的用户为1，未订购为0）",
        "终端是否支持卫星直连功能:终端是否支持卫星直连功能（用户当前手机终端为卫星终端的为1，其他为0）",
        "用户是否开通卫星直连功能:用户是否开通卫星直连功能",
        "昨日是否换卫星通信手机:识别用户昨日是否更换换卫星手机终端（通过用户终端轨迹查看最新手机终端T账期=卫星终端，且T-1账期为非卫星终端的用户打标为1，其他为0）",
        "是否卫星直连机套匹配用户:识别用户当前持有支持卫星功能手机终端，且已订购卫星业务。",
        "当月卫星通话总时长:统计当月卫星通话时长",
        "当月卫星短信发送总条数:统计当月卫星短信总条数",
        "是否卫星直连月活跃用户:卫星活跃判断口径：当月卫星通话或短信次数大于1",
        "客户下小合约数量:统计当前客户下小合约数量",
        "客户下有VOLTE功能的移动终端数:统计客户下有VOLTE功能的移动终端数",
        "双卡槽终端数:统计客户下双卡槽移动终端数",
        "客户下老旧终端数:统计客户下使用时长大于36个月的移动终端数",
        "近3月宽带月均使用时长:用于识别宽带用户近3月月均宽带使用时长，单位小时",
        "近3月宽带月均使用流量:用于识别宽带用户近3月月均宽带使用流量，单位：M",
        "是否有宽带大流量偏好:宽带上月平均使用流量是否大于等于20G为大流量偏好，标签值：0否，1是",
        "是否开通翼支付:识别用户是否为翼支付在网用户",
        "云电脑客户活跃时长:统计云电脑客户当日/当月在线累计时长",
        "客户是否订购云电脑政企版:识别客户是否已订购政企版云电脑",
        "是否有未激活云电脑政企版:识别客户是否已订购政企版云电脑，且是否已激活",
        "客户订购云电脑政企版资源数量:识别客户是否已订购政企云电脑，并统计其名下资源数量",
        "是否云电脑(公众版)用户:判断是否云电脑(公众版)用户",
        "云电脑(公众版)用户活跃度:云电脑(公众版)活跃度：根据公众用户在线时长做排序统计，排名靠前的0~30%为‘高‘，排名为30~60%为‘中‘，排名为60~100%为‘低‘。",
        "云电脑(公众版)收入:云电脑(公众版)用户收入，本月发生数，,通过财务科目编码获取收入",
        "是否云电脑（政企版）客户:判断是否云电脑(政企版)用户",
        "云电脑（政企版）活跃度:云电脑(政企版)活跃度：根据政企客户在线时长做排序统计，排名靠前的0~30%为‘高‘，排名为30~60%为‘中‘，排名为60~100%为‘低‘。",
        "云电脑（政企版）收入:云电脑(政企版)用户收入，本月发生数，,通过财务科目编码获取收入",
        "云电脑（公众版）月均在线时长:云电脑（公众版）用户当月累计在线时长/当月累计天数",
        "客户是否订购云主机:识别客户是否订购云主机",
        "客户订购云主机资源数量:统计客户订购云主机资源数量",
        "客户订购云主机CPU核心数:统计客户订购云主机CPU核心数",
        "是否有不活跃云主机资源:识别客户下云电脑用户，是否有不活跃云主机资源。不活跃口径：当月累计在线时长=0",
        "是否云主机用户:识别用户是否云主机用户",
        "是否订购天翼云盘:识别用户是否订购天翼云盘",
        "天翼云盘用户近30天使用天数:统计天翼云盘用户近30天，登录且使用天数",
        "是否天翼云盘付费会员:识别用户是否天翼云盘付费会员",
        "同客户下天翼云盘的用户数量:统计同一客户名下天翼云盘的数量",
        "是否天翼云盘激活用户:识别用户是否已激活天翼云盘",
        "天翼云盘本月是否活跃过:识别天翼云盘当月初至今是否使用，当月曾登录云盘则视为活跃为0，否则为沉默用户为1",
        "用户本月天翼云盘首次活跃时间:识别用户当月天翼云盘首次活跃时间",
        "客户本月天翼云盘首次活跃时间:识别同一客户下用户本月天翼云盘最早的登录时间为首次活跃时间",
        "客户名下是否有天翼云盘:客户名下是否有天翼云盘",
        "天翼云盘当月是否活跃:识别天翼云盘当月登录1次及以上则为活跃（为0），否则为沉默用户为1",
        "天翼云盘上月使用次数:天翼云盘上月使用次数",
        "天翼云盘上月使用天数:天翼云盘上月使用天数",
        "天翼云盘上月使用流量:天翼云盘上月使用流量",
        "是否量子换卡用户:通过手机卡资源标识，识别已办理量子业务的用户，是否已经换量子卡",
        "量子密话密信当月是否活跃:识别用户是否量子用户是否活跃",
        "量子密信APP使用次数:以下量子业务数据总和,即：用户dangyue 累计发送及接收音视频通话+消息的数量",
        "是否电信员工量子用户:识别量子用户是否电信员工",
        "量子密话密信加密服务次数:以下量子加密业务数据总和,即：加密消息使用次数+",
        "是否真千兆用户:识别用户是否为真千兆用户（千兆网关、千兆套餐、千兆速率）。标签值：1，是；0，否；-1，未知",
        "是否卫星旅游爱好用户:结合用户app使用行为，（例如：打车、酒店住宿、旅游出行、租车以及地图导航类型app），以及用户基站坐标排序分析，最终按照权重规则计算排序得出是否旅游爱好者用户标签。",
        "是否卫星高潜用户:筛选天气、旅行、地图、租车、安全以及新闻和生活服务类app，通过用户的app使用行为：时长、流量、次数以及活跃度，通过计算排序得到最终目标用户。",
        "权益商城购买概率:根据用户使用音视频app行为情况，以及历史购买详情，最终形成分值，计算该用户的权益商城购买概率",
        "综合网格ID:用户入网渠道的综合网格id",
        "综合网格名称:用户入网渠道的综合网格名称",
        "综合网格类型:用户入网渠道的综合网格类型",
        "入网渠道店中商类型:用户入网渠道店中商类型",
        "新入网换终端:开通时间为近三月，且当月有换终端的行为，标签主数据：0，否；1，是",
        "末次终端制式:当前终端制式：CDMA1X手机，EVDO手机，4G手机，5G手机",
        "收入-超套餐流量费-用户-上月:t-1账期数据，流量收入有超套餐行为的用户，即：有财务科目编码=1043(手机上网-套外标准资费)的收入大于0的用户",
        "收入超套餐流量费用户arpu:收入超套餐流量费用户arpu(近三月均值):(t月+t-1月+t-2月)/3",
        "收入-超套餐流量费_用户_本月:t账期数据，流量收入有超套餐行为的用户，即：有财务科目编码=1043(手机上网-套外标准资费)的收入大于0的用户",
        "是否订购流量包:是否订购流量包",
        "流量包订购个数:流量包订购个数",
        "流量包累计免费量:流量包累计免费量",
        "套餐内流量超出标识-月0:套餐内流量超出标识t月，使用流量-主套餐流量(不包含订购流量包)>0",
        "套餐内流量超出标识-月1:套餐内流量超出标识t-1月，使用流量-主套餐流量(不包含订购流量包)>0",
        "是否5G流量用户:是否5G流量用户：包括如下几类：1、订购5G主套餐用户2、订购5G升级包用户3、使用5G终端的用户4、开通5G服务功能的用户5、有5G话单的用户",
        "主卡使用套餐下宽带流量天数_月0:主卡使用套餐下宽带流量天数_月0",
        "主卡使用套餐下宽带流量天数_月1:主卡使用套餐下宽带流量天数_月1",
        "用户是否超套超包流量:有流量额外支出的用户，即：财务科目编码=1043，且税后出账金额大于0",
        "是否当月到期短期流量包:是否当月到期短期流量包，短期即：流量包名称里%日包%，当用户订购多个流量包，取到期最晚的一个",
        "套餐内流量使用量百分比_月1:套餐内流量使用量百分比，即当月使用流量/主套餐流量",
        "套餐内语音使用量百分比_月1:套餐内语音使用量百分比，即当月语音时长/主套餐语音时长",
        "当前主套餐类型:当前主套餐类型",
        "当月是否套餐变更:当月是否套餐变更",
        "是否套餐价值流量不匹配用户:在网老套餐用户的在用主套餐+流量包的总流量远低于当前同价位(指主套餐月费+流量包月费之和)主流套餐的流量",
        "近三月是否套餐变更:用户近三月是否套餐变更",
        "老旧终端:统计同一客户名下使用时长大于36个月的移动终端数",
        "语音骤降客户:客户在所有用户，当月语音总和比前三月语音总和均值下降50%以上，则为骤降，其他为否。标签主数据：1，是；0，否；-1，未知",
        "流量骤降客户:客户在所有用户，当月移动流量使用总和比前三月流量使用总和均值下降50%以上，则为骤降，其他为否。标签主数据：1，是；0，否；-1，未知",
        "同客户名下产品近3个月是否有投诉:同一客户名下，近3月内是否有过投诉行为",
        "同客户名下产品近3个月投诉分类:同一客户名下，近3月内有过投诉行为，记录最新一条投诉类型",
        "国内长期漫游用户:判断用户是否国内长期漫游用户，长期漫游口径：超过六个月连续漫游",
        "国内长期漫游用户名下是否满五张号码:统计国内长期漫游用户，同一客户名下移动产品类型个数，5-当前客户名下移动出账用户数=剩余数量；长期漫游口径：超过六个月连续漫游",
        "免费副卡剩余数量:统计同一客户名下移动产品类型个数，5-当前客户名下移动出账用户数=剩余数量",
        "客户消费层次:统计客户t月税后收入，档次氛围：取值：1、39以下；2、[39,59)；3、[59,99)；4、[99,129)；5、[129,159)；6、[159,199)；7、199以上",
        "近15天沉默标识:识别移动用户连续15天无语音、流量、短音行为的用户（活跃口径：通话总时长+手机sp上行短信次数+点对点短信条数+手机上网流量>0，以上数据均为0，则是沉默）",
        "近30天活跃天数:近30天活跃天数",
        "是否当日到期短期流量包:是否当日到期短期流量包，短期即：流量包名称里%日包%，一般会有1日、3日、5日、7日流量包",
        "近3个月最近一次投诉日期:近3个月最近一次投诉日期",
        "近3个月最近一次投诉标签:近3个月最近一次投诉标签",
        "是否一拆一装:是否一拆一装（先拆后装），标签主数据：0，否；1，是",
        "当月宽带上网总流量:宽带上网使用总流量t月",
        "上月宽带上网总流量:宽带上网使用总流量t-1月",
        "无线网络质差:一、网关wifi承载力和路由器最优承载力关联，能关联上路由器最优承载力的，判断网关Wi-Fi是否使用： 1、是 a、若网关wifi承载力与路由器最优承载力有一个能承载则能承载； 若网关wifi不能承载且路由器最优承载力无法判断，则无法判断； b、若网关wifi承载力与路由器最优承载力都不能承载，则不能承载； c、除a、b外的都为无法判断 2、否，则为路由器最优承载力；二、网关wifi承载力和路由器最优承载力关联，关联不上路由器最优承载力的，判断网关Wi-Fi是否使用： 1、是，则为网关wifi承载力 2、否，能承载"
    
    ]
    
    logger.info(f"开始训练 {len(docs)} 条业务文档...")
    for idx, doc in enumerate(docs):
        try:
            vn.train(documentation=doc)
            if idx % 100 == 0:
                logger.info(f"已训练 {idx}/{len(docs)} 条文档")
        except Exception as e:
            logger.error(f"训练文档失败 (第{idx}条): {doc[:50]}..., 错误: {e}", exc_info=True)
    
    elapsed = time.time() - start_time
    logger.info(f"Vanna 初始化完成，总耗时 {elapsed:.2f} 秒")

def generate_sql(question: str) -> str:
    if vn is None:
        init_vanna()
    logger.info(f"Vanna 收到问题: {question[:80]}...")
    try:
        sql = vn.generate_sql(question=question)
        logger.debug(f"生成的 SQL: {sql}")
        return sql
    except Exception as e:
        logger.error(f"生成 SQL 失败: {e}", exc_info=True)
        raise